# zizmor is a static analysis tool for GitHub Actions workflows that detects
# security issues, misconfigurations, and best-practice violations.
#
# config ref: https://docs.zizmor.sh/configuration/#discovery
# rules ref:  https://docs.zizmor.sh/audits/
#
rules:
  # FIXME: cache-poisoning was disabled on introduction to avoid erroring, try
  #        fix issues or motivate why it should remain disabled
  cache-poisoning:
    disable: true

  # FIXME: excessive-permissions was disabled on introduction to avoid erroring,
  #        try fix issues or motivate why it should remain disabled
  excessive-permissions:
    disable: true

  # FIXME: secrets-outside-env was disabled on introduction to avoid erroring,
  #        try fix issues or motivate why it should remain disabled
  secrets-outside-env:
    disable: true
