# prek (Rust version of the Python based pre-commit) is a tool to perform a
# predefined set of tasks manually and/or automatically before git commits are
# made.
#
# We require prek specifically, since we want support for rust based hooks.
#
# pre-commit reference: https://pre-commit.com/#pre-commit-configyaml---top-level
# prek reference:       https://prek.j178.dev/configuration/
#
# Common tasks
#
# - Run once on all files: prek run -a
# - Register git hooks:    prek install
#
# FIXME: transition to a prek official config as we now require prek
# FIXME: ensure hooks gets updated over time automatically
#
repos:
  # Autoformat: markdown, yaml, json, js
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        exclude: |-
          (?x)(
              stdlib_assets/|
              \.lock
          )

  # Autoformat: rust
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        description: Formats all bin and lib files of the current workspace using rustfmt.
        language: rust
        types: [rust]
        args: ["--"]

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy
        description: Checks all packages in the workspace to catch common mistakes and improve your Rust code.
        language: rust
        types: [rust]
        args:
          - --workspace
          - --all-targets
          - --all-features
          - --allow-dirty
          - --fix
          - --
          - --deny
          - warnings
        pass_filenames: false

  # Autoformat: python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # Lint: python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.0
    hooks:
      - id: mypy
        args:
          - --strict
        # lint only what is known to use typings
        files: |-
          (?x)^(
              bindings/py/python/|
              bindings/java/scripts/
          )

  # Lint: javascript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.1.0
    hooks:
      - id: eslint
        files: ^bindings/js/
        types: [javascript]
        additional_dependencies:
          - eslint@^10.1.0
          - "@eslint/js@^10.0.1"
          - globals@^17.4.0
