# cargo-about is a tool to generate license attribution reports for Rust
# dependencies, intended to be shipped alongside release artifacts.
#
# It is independent of cargo-deny (see deny.toml), which enforces license
# policy at build/CI time. Use both: deny to gate, about to document.
#
# Config reference: https://github.com/EmbarkStudios/cargo-about#configuration
#
# Common tasks
#
# - Generate a license report (JSON): cargo about generate --format json
# - Generate a license report (HTML): cargo about generate <template file, .hbs format>
#
# FIXME:
#
# - we currently error when trying to generate a report
# - this file is outdated and does not list all targets that we support
# - our CI system doesn't care about it currently
#
accepted = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "MPL-2.0",
    "BSD-3-Clause",
    "ISC",
]

targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
private = { ignore = true }
