# syntax = docker/dockerfile:1.27@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM docker.io/library/alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

ARG TARGETARCH

# ca-certificates and curl are added so that they can be used to exchange
# temporary trusted publishing tokens, relevant when using sysand publish in a
# CI context
RUN apk add --no-cache ca-certificates curl

# sysand-amd64-musl / sysand-arm64-musl are populated via the publish-images workflow/job
COPY --chmod=0755 sysand-${TARGETARCH}-musl/sysand /usr/local/bin/sysand
