[toolchain]
channel = "1.85"
components = [ "rustfmt", "clippy", "llvm-tools-preview" ]
targets = [ "x86_64-pc-windows-msvc", "aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu" ]
profile = "minimal"
