# rust-toolchain.toml pins the Rust toolchain version and components so that all
# developers and CI use the same compiler.
#
# Config reference: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
#
# Common tasks
#
# - Check latest stable version: rustup check
#
[toolchain]
channel = "1.94"
components = [ "rustfmt", "clippy" ]
profile = "minimal"
