# ast-grep (https://ast-grep.github.io/) is used essentially as a linter
# for patterns not covered by clippy or dylint.
#
# Config reference: https://ast-grep.github.io/reference/sgconfig
#
# Advisory only, not run in pre-commit or CI
#
# When adding/editing rules with auto-fixes, make sure they
# don't remove comments, since by default comments are ignored
#
# Run all the checks:
# ast-grep scan
# Run a specific check:
# ast-grep scan --rule rules/<rule>.yml
#
# Ignore a specific rule in code for a false-positive
# (put on the preceding or same line):
# // ast-grep-ignore: <rule-id>
ruleDirs:
  - rules
