# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: © 2026 Sysand contributors <opensource@sensmetry.com>

import logging
import tempfile
from pathlib import Path
import re
import os
from typing import List, Union

import pytest
from pytest_httpserver import HTTPServer

import sysand


def test_basic_init(caplog: pytest.LogCaptureFixture) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init("test_basic_init", "a", "1.2.3", tmpdirname)

        assert caplog.record_tuples == [
            (
                "sysand_core.commands.init",
                logging.INFO,
                "    Creating interchange project `test_basic_init`",
            )
        ]
        with open(Path(tmpdirname) / ".project.json", "r") as f:
            assert (
                f.read()
                == '{\n  "name": "test_basic_init",\n  "publisher": "a",\n  "version": "1.2.3"\n}\n'
            )
        with open(Path(tmpdirname) / ".meta.json", "r") as f:
            assert re.match(
                r'\{\n  "index": \{\},\n  "created": "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z"\n}\n',
                f.read(),
            )


def test_basic_env() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        env_path = Path(tmpdirname) / sysand.env.DEFAULT_ENV_NAME
        sysand.env.env(env_path)
        assert env_path.is_dir()
        content = (env_path / "env.toml").read_text()
        assert (
            content
            == '# This file is automatically generated by Sysand and is not intended to be edited manually.\n\nversion = "0.1"\n'
        )


def test_add_accepts_sysand_shorthand() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init("test_add_accepts_sysand_shorthand", "a", "1.2.3", tmpdirname)

        sysand.add(tmpdirname, "acme-labs/my.project")

        assert (
            (Path(tmpdirname) / ".project.json").read_text()
            == '{\n  "name": "test_add_accepts_sysand_shorthand",\n  "publisher": "a",\n  "version": "1.2.3",\n  "usage": [\n    {\n      "resource": "pkg:sysand/acme-labs/my.project"\n    }\n  ]\n}\n'
        )


def test_remove_accepts_sysand_shorthand() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init("test_remove_accepts_sysand_shorthand", "a", "1.2.3", tmpdirname)

        sysand.add(tmpdirname, "acme-labs/my.project")
        sysand.remove(tmpdirname, "acme-labs/my.project")

        assert (
            (Path(tmpdirname) / ".project.json").read_text()
            == '{\n  "name": "test_remove_accepts_sysand_shorthand",\n  "publisher": "a",\n  "version": "1.2.3"\n}\n'
        )


def test_basic_info(caplog: pytest.LogCaptureFixture) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init("test_basic_info", "a", "1.2.3", tmpdirname)

        info_meta = sysand.info_path(tmpdirname)
        assert info_meta is not None

        info, meta = info_meta

        assert info == {
            "name": "test_basic_info",
            "publisher": "a",
            "description": None,
            "version": "1.2.3",
            "license": None,
            "maintainer": [],
            "website": None,
            "topic": [],
            "usage": [],
        }

        assert meta["index"] == {}
        assert isinstance(meta["created"], str)
        assert re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$", meta["created"])
        assert meta["metamodel"] is None
        assert meta["includes_derived"] is None
        assert meta["includes_implied"] is None
        assert meta["checksum"] is None

        file_uri = Path(tmpdirname).resolve().as_uri()

        info_meta2 = sysand.info(file_uri)
        assert info_meta2 == info_meta


def test_http_info(caplog: pytest.LogCaptureFixture, httpserver: HTTPServer) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    httpserver.expect_request("/.project.json").respond_with_json(
        {"name": "test_http_info", "publisher": "a", "version": "1.2.3"}
    )
    httpserver.expect_request("/.meta.json").respond_with_json(
        {"index": {}, "created": "0000-00-00T00:00:00.123456789Z"}
    )

    info, meta = sysand.info(httpserver.url_for(""))

    assert info == {
        "name": "test_http_info",
        "publisher": "a",
        "description": None,
        "version": "1.2.3",
        "license": None,
        "maintainer": [],
        "website": None,
        "topic": [],
        "usage": [],
    }

    assert meta["index"] == {}
    # meta['created'] utc time
    assert meta["metamodel"] is None
    assert meta["includes_derived"] is None
    assert meta["includes_implied"] is None
    assert meta["checksum"] is None


def test_index_info(caplog: pytest.LogCaptureFixture, httpserver: HTTPServer) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    filler_digest = "sha256:" + ("a" * 64)
    # No discovery document: index_root defaults to the discovery root.
    httpserver.expect_request("/sysand-index-config.json").respond_with_data(
        "", status=404
    )
    iri_dir = "/_iri/19148b59a7f258e6eab15189ebcc5b6f884e02690a3b27f3f43e4c6e15dd9536"
    httpserver.expect_request(f"{iri_dir}/versions.json").respond_with_json(
        {
            "versions": [
                {
                    "version": "1.2.3",
                    "usage": [],
                    "kpar_size": 42,
                    "kpar_digest": filler_digest,
                }
            ]
        }
    )
    httpserver.expect_request(f"{iri_dir}/1.2.3/.project.json").respond_with_json(
        {"name": "test_index_info", "version": "1.2.3"}
    )
    httpserver.expect_request(f"{iri_dir}/1.2.3/.meta.json").respond_with_json(
        {"index": {}, "created": "2026-01-01T00:00:00Z"}
    )

    info, meta = sysand.info(
        "urn:kpar:test_index_info", index_urls=httpserver.url_for("")
    )

    assert info["name"] == "test_index_info"
    assert info["version"] == "1.2.3"
    assert info["usage"] == []
    assert info["publisher"] is None

    assert meta["index"] == {}
    assert isinstance(meta["created"], str)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$", meta["created"])
    assert meta["metamodel"] is None
    assert meta["includes_derived"] is None
    assert meta["includes_implied"] is None
    assert meta["checksum"] is None


def compare_sources(
    sources: Union[List[Path], List[str]],
    expected_sources: Union[List[Path], List[str]],
) -> None:
    assert len(sources) == len(expected_sources)
    for source, expected_source in zip(sources, expected_sources):
        assert os.path.samefile(source, expected_source), (
            f"source: {source}, expected_source: {expected_source}"
        )


def test_end_to_end_install_sources() -> None:
    # A standard library is identified by its hard-coded IRI; the version must
    # match the embedded standard library metadata so that every `Dependencies`
    # mode resolves the same usage.
    std_iri = "https://www.omg.org/spec/KerML/20250201/Function-Library.kpar"
    std_version = "1.0.0"

    with (
        tempfile.TemporaryDirectory() as tmp_main,
        tempfile.TemporaryDirectory() as tmp_dep,
        tempfile.TemporaryDirectory() as tmp_std,
    ):
        tmp_main = Path(tmp_main).resolve()
        tmp_dep = Path(tmp_dep).resolve()
        tmp_std = Path(tmp_std).resolve()
        sysand.init("test_end_to_end_install_sources", "a", "1.2.3", tmp_main)
        sysand.init("test_end_to_end_install_sources_dep", "a", "1.2.3", tmp_dep)
        sysand.init("Kernel Function Library", "a", std_version, tmp_std)

        with open(Path(tmp_main) / "src.sysml", "w") as f:
            f.write("package Src;")

        sysand.include(tmp_main, "src.sysml")

        with open(Path(tmp_dep) / "src_dep.sysml", "w") as f:
            f.write("package SrcDep;")

        sysand.include(tmp_dep, "src_dep.sysml")

        with open(Path(tmp_std) / "src_std.sysml", "w") as f:
            f.write("package SrcStd;")

        sysand.include(tmp_std, "src_std.sysml")

        env_path = Path(tmp_main) / sysand.env.DEFAULT_ENV_NAME

        sysand.env.env(env_path)

        sysand.env.install_path(
            env_path, "urn:kpar:test_end_to_end_install_sources_dep", tmp_dep
        )
        sysand.env.install_path(env_path, std_iri, tmp_std)

        sysand.add(tmp_main, "urn:kpar:test_end_to_end_install_sources_dep", "1.2.3")
        sysand.add(tmp_main, std_iri, std_version)

        dep_src = (
            env_path
            / "lib"
            / "kpar.test_end_to_end_install_sources_dep_1.2.3"
            / "src_dep.sysml"
        )

        [std_src] = (env_path / "lib").glob("*/src_std.sysml")

        # By default only the project's own sources are listed.
        compare_sources(
            sysand.sources(tmp_main),
            [str(Path(tmp_main) / "src.sysml")],
        )
        compare_sources(
            sysand.sources(tmp_dep),
            [str(Path(tmp_dep) / "src_dep.sysml")],
        )
        # Own sources together with dependency sources, excluding std libs.
        compare_sources(
            sysand.sources(
                tmp_main, dependencies=sysand.Dependencies.DEPS, env_path=env_path
            ),
            [str(Path(tmp_main) / "src.sysml"), str(dep_src)],
        )
        # Only dependency sources.
        compare_sources(
            sysand.sources(
                tmp_main,
                no_own=True,
                dependencies=sysand.Dependencies.DEPS,
                env_path=env_path,
            ),
            [str(dep_src)],
        )
        # no_own without dependencies yields nothing.
        compare_sources(sysand.sources(tmp_main, no_own=True), [])

        # DEPS_STD includes both the dependency and the std lib.
        compare_sources(
            sorted(
                sysand.sources(
                    tmp_main,
                    no_own=True,
                    dependencies=sysand.Dependencies.DEPS_STD,
                    env_path=env_path,
                ),
                key=lambda p: Path(p).name,
            ),
            sorted([str(dep_src), str(std_src)], key=lambda p: Path(p).name),
        )
        # STD includes only the std lib.
        compare_sources(
            sysand.sources(
                tmp_main,
                no_own=True,
                dependencies=sysand.Dependencies.STD,
                env_path=env_path,
            ),
            [str(std_src)],
        )

        sysand.exclude(tmp_main, "src.sysml")

        compare_sources(
            sysand.sources(
                tmp_main, dependencies=sysand.Dependencies.DEPS, env_path=env_path
            ),
            [str(dep_src)],
        )
        compare_sources(
            sysand.sources(
                tmp_main,
                no_own=True,
                dependencies=sysand.Dependencies.DEPS,
                env_path=env_path,
            ),
            [str(dep_src)],
        )


def test_root() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        tmpdirname = Path(tmpdirname).resolve()
        sysand.init("test_root", "a", "1.2.3", tmpdirname)

        subdir = tmpdirname / "sub" / "nested"
        subdir.mkdir(parents=True)

        root_from_top = sysand.root(tmpdirname)
        root_from_sub = sysand.root(subdir)

        assert root_from_top is not None
        assert root_from_sub is not None
        assert os.path.samefile(root_from_top, tmpdirname)
        assert os.path.samefile(root_from_sub, tmpdirname)


def test_root_not_in_project() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        assert sysand.root(tmpdirname) is None


@pytest.mark.parametrize(
    "compression",
    [None, sysand.CompressionMethod.STORED, sysand.CompressionMethod.DEFLATED],
)
def test_build(compression: Union[sysand.CompressionMethod, None]) -> None:
    with tempfile.TemporaryDirectory() as tmp_main:
        tmp_main = Path(tmp_main).resolve()
        sysand.init("test_build", "a", "1.2.3", tmp_main)

        with open(tmp_main / "src.sysml", "w") as f:
            f.write("package Src;")

        sysand.include(tmp_main, "src.sysml")

        sysand.build(
            output_path=tmp_main / "test_build.kpar",
            project_path=tmp_main,
            compression=compression,
        )
