# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: © 2026 Sysand contributors <opensource@sensmetry.com>

import json
import logging
import tempfile
from pathlib import Path
import os
import typing
import re
from typing import Callable, List, Union

import pytest
from pytest_httpserver import HTTPServer

import sysand
from mockindex import MockIndex, run_cli_in


def test_basic_init(caplog: pytest.LogCaptureFixture) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init(
            project_dir=tmpdirname,
            name="test_basic_init",
            publisher="a",
            version="1.2.3",
        )

        assert caplog.record_tuples == [
            (
                "sysand_core.commands.init",
                logging.INFO,
                "    Creating interchange project `test_basic_init`",
            )
        ]
        with open(Path(tmpdirname) / ".project.json", "r") as f:
            assert (
                f.read()
                == '{\n  "name": "test_basic_init",\n  "publisher": "a",\n  "version": "1.2.3"\n}\n'
            )
        with open(Path(tmpdirname) / ".meta.json", "r") as f:
            assert re.match(
                r'\{\n  "index": \{\},\n  "created": "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z"\n}\n',
                f.read(),
            )


def test_basic_env() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        env_path = Path(tmpdirname) / sysand.env.DEFAULT_ENV_NAME
        sysand.env.env(path=env_path)
        assert env_path.is_dir()
        content = (env_path / "env.toml").read_text()
        assert (
            content
            == '# This file is automatically generated by Sysand and is not intended to be edited manually.\n\nversion = "0.1"\n'
        )


def test_add_by_publisher_and_name() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init(
            project_dir=tmpdirname,
            name="test_add_by_publisher_and_name",
            publisher="a",
            version="1.2.3",
        )

        sysand.add(
            project_dir=tmpdirname,
            publisher="acme-labs",
            name="my.project",
            version_constraint="*",
        )

        assert (
            (Path(tmpdirname) / ".project.json").read_text()
            == '{\n  "name": "test_add_by_publisher_and_name",\n  "publisher": "a",\n  "version": "1.2.3",\n  "usage": [\n    {\n      "publisher": "acme-labs",\n      "name": "my.project",\n      "versionConstraint": "*"\n    }\n  ]\n}\n'
        )


def test_remove_by_publisher_and_name() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init(
            project_dir=tmpdirname,
            name="test_remove_by_publisher_and_name",
            publisher="a",
            version="1.2.3",
        )

        sysand.add(
            project_dir=tmpdirname,
            publisher="acme-labs",
            name="my.project",
            version_constraint="*",
        )
        sysand.remove(project_dir=tmpdirname, publisher="acme-labs", name="my.project")

        assert (
            (Path(tmpdirname) / ".project.json").read_text()
            == '{\n  "name": "test_remove_by_publisher_and_name",\n  "publisher": "a",\n  "version": "1.2.3"\n}\n'
        )


def test_the_shorthand_is_not_an_iri(tmp_path: Path) -> None:
    # `publisher/name` used to be expanded; now it is refused as the relative
    # reference it is, rather than silently written, or reported "not found".
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    with pytest.raises(sysand.ProjectError):
        sysand.add(
            project_dir=tmp_path, iri="acme-labs/my.project", version_constraint="*"
        )
    with pytest.raises(sysand.ProjectError):
        sysand.remove(project_dir=tmp_path, iri="mock/library")
    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            iri="mock/library",
            version_constraint="1.0.0",
            must_exist=False,
        )
    assert "not declared" not in str(excinfo.value)

    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST


SYSAND_FORMATTED_MANIFEST = """{
  "version": "1.2.3",
  "name": "fidelity",
  "x-unknown-top-level": {
    "kept": true
  },
  "publisher": "acme",
  "usage": [
    {
      "dir": "../local-lib",
      "publisher": "local-pub",
      "name": "local-lib"
    },
    {
      "x-unknown-in-usage": null,
      "resource": "pkg:sysand/mock/library",
      "versionConstraint": ">=0.10.0, <0.11.0"
    }
  ]
}
"""


def _one_line_diff(before: str, after: str) -> tuple[str, str]:
    old_lines = before.splitlines(keepends=True)
    new_lines = after.splitlines(keepends=True)
    assert len(old_lines) == len(new_lines)
    differing = [(o, n) for o, n in zip(old_lines, new_lines) if o != n]
    assert len(differing) == 1, differing
    return differing[0]


def test_set_usage_constraint_preserves_document(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    change = sysand.set_usage_constraint(
        project_dir=tmp_path,
        iri="pkg:sysand/mock/library",
        version_constraint=">=0.11.0, <0.12.0",
    )

    assert change == {
        "found": True,
        "changed": True,
        "old_version_constraint": ">=0.10.0, <0.11.0",
        "new_version_constraint": ">=0.11.0, <0.12.0",
    }
    old_line, new_line = _one_line_diff(SYSAND_FORMATTED_MANIFEST, manifest.read_text())
    assert old_line == '      "versionConstraint": ">=0.10.0, <0.11.0"\n'
    assert new_line == '      "versionConstraint": ">=0.11.0, <0.12.0"\n'


def test_set_usage_constraint_by_iri(
    tmp_path: Path,
) -> None:
    (tmp_path / ".project.json").write_text(SYSAND_FORMATTED_MANIFEST)
    change = sysand.set_usage_constraint(
        project_dir=tmp_path, iri="pkg:sysand/mock/library", version_constraint="0.11.0"
    )
    assert change["found"] and change["changed"]
    assert change["new_version_constraint"] == "0.11.0"


def test_set_usage_constraint_cannot_clear(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    with pytest.raises(TypeError):
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            publisher="mock",
            name="library",
            version_constraint=None,  # type: ignore[call-overload]
        )
    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST


def test_set_usage_constraint_appends_a_missing_constraint(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(
        SYSAND_FORMATTED_MANIFEST.replace(
            ',\n      "versionConstraint": ">=0.10.0, <0.11.0"', ""
        )
    )

    # Setting a constraint on a usage without one appends it as the last key.
    change = sysand.set_usage_constraint(
        project_dir=tmp_path,
        iri="pkg:sysand/mock/library",
        version_constraint="^0.11",
    )
    assert change["old_version_constraint"] is None
    assert change["new_version_constraint"] == "^0.11"
    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST.replace(
        ">=0.10.0, <0.11.0", "^0.11"
    )


def test_set_usage_constraint_unchanged_does_not_touch_file(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)
    os.utime(manifest, ns=(1_000_000_000_000_000_000, 1_000_000_000_000_000_000))
    before = manifest.stat()

    change = sysand.set_usage_constraint(
        project_dir=tmp_path,
        iri="pkg:sysand/mock/library",
        version_constraint=">=0.10.0, <0.11.0",
    )

    assert change["found"] is True
    assert change["changed"] is False
    assert (
        change["old_version_constraint"]
        == change["new_version_constraint"]
        == ">=0.10.0, <0.11.0"
    )
    after = manifest.stat()
    assert after.st_mtime_ns == before.st_mtime_ns
    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST


def test_set_usage_constraint_not_found(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            publisher="acme",
            name="absent",
            version_constraint="1.0.0",
        )
    assert excinfo.value.wrote is False
    assert isinstance(excinfo.value, RuntimeError)
    assert "usage `acme/absent` is not declared" in str(excinfo.value)

    change = sysand.set_usage_constraint(
        project_dir=tmp_path,
        publisher="acme",
        name="absent",
        version_constraint="1.0.0",
        must_exist=False,
    )
    assert change == {
        "found": False,
        "changed": False,
        "old_version_constraint": None,
        "new_version_constraint": None,
    }
    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST

    # A missing manifest is an error even with must_exist=False.
    with pytest.raises(sysand.ProjectError):
        sysand.set_usage_constraint(
            project_dir=tmp_path / "nowhere",
            publisher="acme",
            name="absent",
            version_constraint="1.0.0",
            must_exist=False,
        )


def test_set_usage_constraint_rejects_bad_input(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    # The same faults `add` and `remove` reject, rejected the same way.
    with pytest.raises(sysand.ProjectError):
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            iri="pkg:sysand/mock/library",
            version_constraint="nonsense",
        )
    with pytest.raises(sysand.ProjectError):
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            publisher="ab",
            name="proj0",
            version_constraint="1.0.0",
        )
    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST

    manifest.write_text(
        SYSAND_FORMATTED_MANIFEST.replace(
            '"dir": "../local-lib"', '"resource": "pkg:sysand/mock/library"'
        )
    )
    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            iri="pkg:sysand/mock/library",
            version_constraint="1.0.0",
        )
    assert "2 times" in str(excinfo.value)
    assert excinfo.value.wrote is False


def test_set_usage_constraint_normalizes_hand_formatted_whitespace(
    tmp_path: Path,
) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(
        '{"name":"hand","version":"1.0.0","usage":[{"resource":"a:b","versionConstraint":"1.0.0"}],"z":1}'
    )
    sysand.set_usage_constraint(
        project_dir=tmp_path, iri="a:b", version_constraint="2.0.0"
    )
    # Same keys, same order, sysand's whitespace.
    assert (
        manifest.read_text()
        == """{
  "name": "hand",
  "version": "1.0.0",
  "usage": [
    {
      "resource": "a:b",
      "versionConstraint": "2.0.0"
    }
  ],
  "z": 1
}
"""
    )


def test_add_returns_whether_a_usage_was_added(tmp_path: Path) -> None:
    sysand.init(
        project_dir=tmp_path, name="test_add_returns", publisher="a", version="1.2.3"
    )

    def add_mine() -> bool:
        return sysand.add(
            project_dir=tmp_path,
            publisher="acme-labs",
            name="my.project",
            version_constraint=">=1.0.0",
        )

    assert add_mine() is True
    assert add_mine() is False
    assert (
        sysand.add(
            project_dir=tmp_path,
            iri="pkg:sysand/acme-labs/other",
            version_constraint="*",
        )
        is True
    )


def test_set_usage_constraint_refuses_a_usage_that_cannot_hold_one(
    tmp_path: Path,
) -> None:
    # The directory usage in the fixture *is* the project `local-pub/local-lib`.
    # Reporting it as "not declared" would be false, and setting a constraint
    # on it is meaningless: a directory holds one version.
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            publisher="local-pub",
            name="local-lib",
            version_constraint="1.0.0",
        )
    assert "directory usage" in str(excinfo.value)
    assert excinfo.value.wrote is False

    # `must_exist=False` means "absent is fine". This usage is not absent.
    with pytest.raises(sysand.ProjectError):
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            publisher="local-pub",
            name="local-lib",
            version_constraint="1.0.0",
            must_exist=False,
        )

    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST


def test_remove_returns_the_removed_usages(tmp_path: Path) -> None:
    sysand.init(
        project_dir=tmp_path, name="test_remove_returns", publisher="a", version="1.2.3"
    )
    sysand.add(
        project_dir=tmp_path,
        publisher="acme-labs",
        name="my.project",
        version_constraint=">=1.0.0",
    )

    removed = sysand.remove(
        project_dir=tmp_path, publisher="acme-labs", name="my.project"
    )

    assert removed == [
        {
            "publisher": "acme-labs",
            "name": "my.project",
            "version_constraint": ">=1.0.0",
        }
    ]


def test_usages_read_back_by_how_they_are_found(tmp_path: Path) -> None:
    sysand.init(project_dir=tmp_path, name="proj", publisher="acme", version="1.0.0")
    sysand.add(
        project_dir=tmp_path,
        publisher="acme-labs",
        name="by.index",
        version_constraint="*",
    )
    # A `pkg:sysand` IRI is a resource usage, taken literally.
    sysand.add(
        project_dir=tmp_path,
        iri="pkg:sysand/acme-labs/by.iri",
        version_constraint="^1.0",
    )
    sysand.add(
        project_dir=tmp_path,
        iri="https://example.com/by-url.kpar",
        version_constraint="*",
    )

    info, _ = sysand.info_path(project_dir=tmp_path)

    assert info["usage"] == [
        {"publisher": "acme-labs", "name": "by.index", "version_constraint": "*"},
        {"resource": "pkg:sysand/acme-labs/by.iri", "version_constraint": "^1.0"},
        {"resource": "https://example.com/by-url.kpar", "version_constraint": "*"},
    ]
    manifest = json.loads((tmp_path / ".project.json").read_text())
    assert manifest["usage"][0] == {
        "publisher": "acme-labs",
        "name": "by.index",
        "versionConstraint": "*",
    }


def _declare_dir_usage(root: Path) -> None:
    """Declare `acme-labs/my.project` in `../dep` in the project at `root`,
    by editing the manifest: the Python API cannot add a directory usage."""
    manifest_path = root / ".project.json"
    manifest = json.loads(manifest_path.read_text())
    manifest["usage"] = [
        {"dir": "../dep", "publisher": "acme-labs", "name": "my.project"}
    ]
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")


def test_remove_refuses_a_usage_of_another_kind(tmp_path: Path) -> None:
    root = tmp_path / "proj"
    sysand.init(project_dir=root, name="proj", publisher="acme", version="1.0.0")
    _declare_dir_usage(root)

    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.remove(project_dir=root, publisher="acme-labs", name="my.project")
    message = str(excinfo.value)
    assert "declared as a directory usage" in message
    assert "Python API cannot remove directory and KPAR usages yet" in message
    assert "could not find" not in message
    assert "sysand experimental" not in message

    # Still declared.
    info, _ = sysand.info_path(project_dir=root)
    assert len(info["usage"]) == 1


def test_remove_still_reports_an_absent_usage(tmp_path: Path) -> None:
    sysand.init(project_dir=tmp_path, name="proj", publisher="acme", version="1.0.0")

    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.remove(project_dir=tmp_path, publisher="acme-labs", name="absent")
    assert "could not find usage" in str(excinfo.value)


def test_add_refuses_a_project_already_declared_as_another_kind(
    tmp_path: Path,
) -> None:
    root = tmp_path / "proj"
    sysand.init(project_dir=root, name="proj", publisher="acme", version="1.0.0")
    _declare_dir_usage(root)

    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.add(
            project_dir=root,
            publisher="acme-labs",
            name="my.project",
            version_constraint="*",
        )
    message = str(excinfo.value)
    assert "already declared as a directory usage" in message
    # The core message says to remove it first, which Python cannot do.
    assert "Python API cannot remove directory and KPAR usages yet" in message

    info, _ = sysand.info_path(project_dir=root)
    assert len(info["usage"]) == 1


def test_publisher_and_name_are_kept_as_spelled(tmp_path: Path) -> None:
    sysand.init(project_dir=tmp_path, name="proj", publisher="acme", version="1.0.0")
    manifest = tmp_path / ".project.json"

    sysand.add(
        project_dir=tmp_path,
        publisher="Acme Labs",
        name="My.Project",
        version_constraint="*",
    )
    assert '"publisher": "Acme Labs"' in manifest.read_text()
    info, _ = sysand.info_path(project_dir=tmp_path)
    assert info["usage"] == [
        {"publisher": "Acme Labs", "name": "My.Project", "version_constraint": "*"}
    ]

    change = sysand.set_usage_constraint(
        project_dir=tmp_path,
        publisher="Acme Labs",
        name="My.Project",
        version_constraint="^1",
    )
    assert change["found"] and change["changed"]

    # Another spelling of the same project names no usage, and says so
    before = manifest.read_text()
    with pytest.raises(
        sysand.ProjectError,
        match="already declared as the index usage `Acme Labs/My.Project`",
    ):
        sysand.add(
            project_dir=tmp_path,
            publisher="acme-labs",
            name="my.project",
            version_constraint="^1",
        )
    with pytest.raises(
        sysand.ProjectError, match="did you mean `Acme Labs/My.Project`"
    ):
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            publisher="acme-labs",
            name="my.project",
            version_constraint="^2",
            must_exist=False,
        )
    with pytest.raises(
        sysand.ProjectError, match="did you mean `Acme Labs/My.Project`"
    ):
        sysand.remove(project_dir=tmp_path, publisher="acme-labs", name="my.project")
    # Nor does its PURL
    with pytest.raises(sysand.ProjectError, match="name it by `publisher` and `name`"):
        sysand.remove(project_dir=tmp_path, iri="pkg:sysand/acme-labs/my.project")
    assert manifest.read_text() == before

    removed = sysand.remove(
        project_dir=tmp_path, publisher="Acme Labs", name="My.Project"
    )
    assert removed == [
        {"publisher": "Acme Labs", "name": "My.Project", "version_constraint": "^1"}
    ]


def test_a_legacy_purl_is_named_by_its_iri(tmp_path: Path) -> None:
    sysand.init(project_dir=tmp_path, name="proj", publisher="acme", version="1.0.0")
    sysand.add(
        project_dir=tmp_path, iri="pkg:sysand/acme-labs/lib", version_constraint="^1"
    )

    with pytest.raises(
        sysand.ProjectError, match="already declared as a resource usage"
    ):
        sysand.add(
            project_dir=tmp_path,
            publisher="acme-labs",
            name="lib",
            version_constraint="^1",
        )
    with pytest.raises(sysand.ProjectError, match="name it by `iri`"):
        sysand.remove(project_dir=tmp_path, publisher="acme-labs", name="lib")
    with pytest.raises(sysand.ProjectError, match="not as an index usage"):
        sysand.set_usage_constraint(
            project_dir=tmp_path,
            publisher="acme-labs",
            name="lib",
            version_constraint="^2",
        )

    assert sysand.remove(project_dir=tmp_path, iri="pkg:sysand/acme-labs/lib") == [
        {"resource": "pkg:sysand/acme-labs/lib", "version_constraint": "^1"}
    ]


def test_add_refuses_an_invalid_publisher_or_name(tmp_path: Path) -> None:
    sysand.init(project_dir=tmp_path, name="proj", publisher="acme", version="1.0.0")

    for publisher, name in [
        ("ab", "proj0"),  # publisher too short
        ("acme/labs", "proj"),  # would be a third PURL segment
        ("acme", "my..project"),  # two separators in a row
    ]:
        with pytest.raises(sysand.ProjectError):
            sysand.add(
                project_dir=tmp_path,
                publisher=publisher,
                name=name,
                version_constraint="*",
            )

    info, _ = sysand.info_path(project_dir=tmp_path)
    assert info["usage"] == []


@pytest.mark.parametrize(
    "call",
    [
        pytest.param(
            lambda p, **kw: sysand.add(project_dir=p, version_constraint="*", **kw),
            id="add",
        ),
        pytest.param(lambda p, **kw: sysand.remove(project_dir=p, **kw), id="remove"),
        pytest.param(
            lambda p, **kw: sysand.set_usage_constraint(
                project_dir=p, version_constraint="1.0.0", **kw
            ),
            id="set_usage_constraint",
        ),
    ],
)
@pytest.mark.parametrize(
    "kwargs",
    [
        pytest.param({}, id="neither"),
        pytest.param(
            {"iri": "pkg:sysand/acme/lib", "publisher": "acme", "name": "lib"},
            id="both",
        ),
        pytest.param({"publisher": "acme"}, id="publisher-only"),
        pytest.param({"iri": "pkg:sysand/acme/lib", "name": "lib"}, id="iri-and-name"),
    ],
)
def test_the_dependency_is_named_exactly_once(
    tmp_path: Path,
    call: Callable[..., object],
    kwargs: dict[str, str],
) -> None:
    # Overloads make each of these a type error too; this pins the runtime
    # behaviour for callers who are not type-checked.
    sysand.init(project_dir=tmp_path, name="proj", publisher="acme", version="1.0.0")
    before = (tmp_path / ".project.json").read_text()

    with pytest.raises(TypeError):
        call(tmp_path, **kwargs)

    assert (tmp_path / ".project.json").read_text() == before


def test_add_needs_a_version_constraint(tmp_path: Path) -> None:
    sysand.init(project_dir=tmp_path, name="proj", publisher="acme", version="1.0.0")

    for kwargs in [
        {"publisher": "acme", "name": "lib"},
        {"iri": "pkg:sysand/acme/lib"},
        {"iri": "https://example.com/lib.kpar"},
    ]:
        with pytest.raises(TypeError):
            sysand.add(project_dir=tmp_path, **kwargs)
        with pytest.raises(TypeError, match='"\\*"'):
            sysand.add(project_dir=tmp_path, version_constraint=None, **kwargs)  # type: ignore[call-overload]
    # Directory and KPAR usages are not reachable yet.
    with pytest.raises(TypeError):
        sysand.add(  # type: ignore[call-overload]
            project_dir=tmp_path,
            usage={"dir": "../dep", "publisher": "acme", "name": "dep"},
        )

    info, _ = sysand.info_path(project_dir=tmp_path)
    assert info["usage"] == []


def _project_with_dir_usage(tmp_path: Path) -> tuple[Path, Path]:
    """A project using a sibling directory project, locked and synced offline
    by the shipped CLI, plus a `urn:kpar:dep` project installed by path."""
    root = tmp_path / "proj"
    dep = tmp_path / "dir-dep"
    kpar_dep = tmp_path / "kpar-dep"
    for name, path in [("proj", root), ("dir-dep", dep), ("kpar-dep", kpar_dep)]:
        path.mkdir()
        sysand.init(project_dir=path, name=name, publisher="acme", version="1.0.0")
        (path / f"{name}.sysml").write_text(f"package P_{name.replace('-', '_')};")
        sysand.include(project_dir=path, src_path=f"{name}.sysml")
    manifest = json.loads((root / ".project.json").read_text())
    manifest["usage"] = [{"dir": "../dir-dep", "publisher": "acme", "name": "dir-dep"}]
    (root / ".project.json").write_text(json.dumps(manifest, indent=2) + "\n")
    assert run_cli_in(root, "lock", "--no-config", "--no-index") == 0
    assert run_cli_in(root, "sync", "--no-config", "--no-index") == 0
    env_dir = root / sysand.env.DEFAULT_ENV_NAME
    # After `sync`, which prunes anything not in the lockfile.
    sysand.env.install_path(env_path=env_dir, iri="urn:kpar:dep", location=kpar_dep)
    return root, env_dir


def test_env_projects_lists_installed_and_editable(tmp_path: Path) -> None:
    root, env_dir = _project_with_dir_usage(tmp_path)

    projects = {p["name"]: p for p in sysand.env.projects(env_path=env_dir)}
    assert set(projects) == {"proj", "dir-dep", "kpar-dep"}
    for project in projects.values():
        assert set(project) == set(sysand.EnvProject.__annotations__)

    # The locked project itself is the environment's editable entry: `path`
    # is relative to the project root and it has no identifiers.
    own = projects["proj"]
    assert own["editable"] is True
    assert own["workspace"] is False
    assert own["publisher"] == "acme"
    assert own["version"] == "1.0.0"
    assert own["identifiers"] == []
    assert os.path.samefile(root / own["path"], root)
    assert own["usages"] == ["pkg:sysand/acme/dir-dep"]
    assert own["checksum"] is None

    # A directory usage is installed as a copy, relative to the env dir.
    dir_dep = projects["dir-dep"]
    assert dir_dep["editable"] is False
    assert dir_dep["identifiers"][0] == "pkg:sysand/acme/dir-dep"
    assert (env_dir / dir_dep["path"] / "dir-dep.sysml").is_file()
    assert dir_dep["usages"] == []
    # Installed from a source directory, so `env.toml` records `src_cksum`.
    assert set(dir_dep["checksum"]) == {"src_cksum"}
    assert re.fullmatch(r"[0-9a-f]{64}", dir_dep["checksum"]["src_cksum"])

    kpar_dep = projects["kpar-dep"]
    assert kpar_dep["editable"] is False
    assert kpar_dep["identifiers"] == ["urn:kpar:dep"]
    assert (env_dir / kpar_dep["path"] / "kpar-dep.sysml").is_file()
    assert kpar_dep["path"].startswith("lib/")


def test_env_sources_is_exported(tmp_path: Path) -> None:
    root, env_dir = _project_with_dir_usage(tmp_path)
    [kpar_dep] = [
        p for p in sysand.env.projects(env_path=env_dir) if p["name"] == "kpar-dep"
    ]

    [source] = sysand.env.sources(env_path=env_dir, iri="urn:kpar:dep")

    assert os.path.samefile(source, env_dir / kpar_dep["path"] / "kpar-dep.sysml")
    assert "sources" in sysand.env.__all__


def test_env_projects_missing_env(tmp_path: Path) -> None:
    with pytest.raises(sysand.EnvError) as excinfo:
        sysand.env.projects(env_path=tmp_path / "nope")
    assert excinfo.value.wrote is False
    assert isinstance(excinfo.value, RuntimeError)
    assert isinstance(excinfo.value, sysand.SysandError)

    # The same failure raises the same class from `install_path`.
    with pytest.raises(sysand.EnvError):
        sysand.env.install_path(
            env_path=tmp_path / "nope", iri="urn:kpar:x", location=tmp_path
        )


def test_discover(tmp_path: Path) -> None:
    assert sysand.discover(path=tmp_path) == {
        "project_root": None,
        "workspace_root": None,
    }

    root = tmp_path / "ws" / "proj"
    root.mkdir(parents=True)
    sysand.init(project_dir=root, name="discover", publisher="acme", version="1.0.0")
    nested = root / "src" / "deep"
    nested.mkdir(parents=True)

    for start in (root, nested):
        found = sysand.discover(path=start)
        assert found["project_root"] is not None
        assert os.path.samefile(found["project_root"], root)
        assert found["workspace_root"] is None
    assert sysand.discover(path=root)["project_root"] == str(sysand.root(path=root))

    (tmp_path / "ws" / ".workspace.json").write_text('{"projects": []}\n')
    found = sysand.discover(path=nested)
    assert found["workspace_root"] is not None
    assert os.path.samefile(found["workspace_root"], tmp_path / "ws")
    assert found["project_root"] is not None
    assert os.path.samefile(found["project_root"], root)
    assert sysand.discover(path=tmp_path / "ws")["project_root"] is None

    (tmp_path / "ws" / ".workspace.json").write_text("not json")
    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.discover(path=root)
    assert excinfo.value.wrote is False


def test_basic_info(caplog: pytest.LogCaptureFixture) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init(
            project_dir=tmpdirname,
            name="test_basic_info",
            publisher="a",
            version="1.2.3",
        )

        info_meta = sysand.info_path(project_dir=tmpdirname)
        assert info_meta is not None

        info, meta = info_meta

        assert info == {
            "name": "test_basic_info",
            "publisher": "a",
            "description": None,
            "version": "1.2.3",
            "license": None,
            "maintainer": [],
            "website": None,
            "topic": [],
            "usage": [],
        }

        assert meta["index"] == {}
        assert isinstance(meta["created"], str)
        assert re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$", meta["created"])
        assert meta["metamodel"] is None
        assert meta["includes_derived"] is None
        assert meta["includes_implied"] is None
        assert meta["checksum"] is None

        file_uri = Path(tmpdirname).resolve().as_uri()

        info_meta2 = sysand.info(iri=file_uri)
        assert info_meta2 == info_meta


def test_http_info(caplog: pytest.LogCaptureFixture, httpserver: HTTPServer) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    httpserver.expect_request("/.project.json").respond_with_json(
        {"name": "test_http_info", "publisher": "a", "version": "1.2.3"}
    )
    httpserver.expect_request("/.meta.json").respond_with_json(
        {"index": {}, "created": "0000-00-00T00:00:00.123456789Z"}
    )

    info, meta = sysand.info(iri=httpserver.url_for(""))

    assert info == {
        "name": "test_http_info",
        "publisher": "a",
        "description": None,
        "version": "1.2.3",
        "license": None,
        "maintainer": [],
        "website": None,
        "topic": [],
        "usage": [],
    }

    assert meta["index"] == {}
    # meta['created'] utc time
    assert meta["metamodel"] is None
    assert meta["includes_derived"] is None
    assert meta["includes_implied"] is None
    assert meta["checksum"] is None


def test_index_info(caplog: pytest.LogCaptureFixture, mock_index: MockIndex) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    # Non-PURL IRIs live under `/_iri/<sha256hex>/`; the fixture serves the
    # real index layout, with no discovery document (index_root defaults to
    # the discovery root).
    mock_index.publish("urn:kpar:test_index_info", "1.2.3")

    info, meta = sysand.info(
        iri="urn:kpar:test_index_info",
        resolution=sysand.Resolution(default_index=[mock_index.url], use_config=False),
    )

    assert info["name"] == "test_index_info"
    assert info["version"] == "1.2.3"
    assert info["usage"] == []
    assert info["publisher"] is None

    assert meta["index"] == {}
    assert isinstance(meta["created"], str)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$", meta["created"])
    assert meta["metamodel"] is None
    assert meta["includes_derived"] is None
    assert meta["includes_implied"] is None
    assert meta["checksum"] is None

    iri_dir = "/_iri/19148b59a7f258e6eab15189ebcc5b6f884e02690a3b27f3f43e4c6e15dd9536"
    assert mock_index.requests("*/versions.json") == [f"{iri_dir}/versions.json"]
    assert mock_index.requests("/index.json") == []


def test_model_roundtrip() -> None:
    # Round-trips the typed dicts through the Rust model types
    from sysand._sysand_core import _do_model_roundtrip_py  # type: ignore

    info: sysand.InterchangeProjectInfo = {
        "name": "roundtrip-project",
        "publisher": "acme",
        "description": "A project with every exposed info field",
        "version": "1.2.3",
        "license": "MIT",
        "maintainer": ["Alice", "Bob"],
        "website": "https://example.com/roundtrip",
        "topic": ["sysml", "bindings"],
        "usage": [
            sysand.InterchangeProjectUsageResource(
                resource="https://example.com/remote-lib.kpar",
                version_constraint=">=1.0.0",
            ),
            sysand.InterchangeProjectUsageIndex(
                publisher="acme",
                name="index-lib",
                version_constraint="^2.0",
            ),
            sysand.InterchangeProjectUsageDirectory(
                dir="../local-lib", publisher="local-pub", name="local-lib"
            ),
            sysand.InterchangeProjectUsageKparPath(
                kpar_path="deps/archive-lib.kpar",
                publisher="archive-pub",
                name="archive-lib",
            ),
        ],
    }

    metadata: sysand.InterchangeProjectMetadata = {
        "index": {"Alpha": "src/Alpha.sysml", "Beta": "src/nested/Beta.kerml"},
        "created": "2026-01-02T03:04:05Z",
        "metamodel": "https://www.omg.org/spec/SysML/20250201",
        "includes_derived": True,
        "includes_implied": False,
        "checksum": {
            "src/Alpha.sysml": sysand.InterchangeProjectChecksum(
                value="0123456789abcdef", algorithm="MD5"
            ),
            "src/nested/Beta.kerml": sysand.InterchangeProjectChecksum(
                value="deadbeef", algorithm="ADLER32"
            ),
        },
    }

    roundtripped_info, roundtripped_metadata = _do_model_roundtrip_py(info, metadata)

    assert roundtripped_info == info
    assert roundtripped_metadata == metadata


def _model_roundtrip(
    usage: typing.List[sysand.InterchangeProjectUsage],
) -> typing.List[sysand.InterchangeProjectUsage]:
    from sysand._sysand_core import _do_model_roundtrip_py  # type: ignore

    info: sysand.InterchangeProjectInfo = {
        "name": "proj",
        "publisher": "acme",
        "description": None,
        "version": "1.0.0",
        "license": None,
        "maintainer": [],
        "website": None,
        "topic": [],
        "usage": usage,
    }
    metadata: sysand.InterchangeProjectMetadata = {
        "index": {},
        "created": "2026-01-02T03:04:05Z",
        "metamodel": None,
        "includes_derived": None,
        "includes_implied": None,
        "checksum": None,
    }
    roundtripped_info, _ = _do_model_roundtrip_py(info, metadata)
    return roundtripped_info["usage"]  # type: ignore[no-any-return]


def test_usages_round_trip_as_given() -> None:
    usage: typing.List[sysand.InterchangeProjectUsage] = [
        sysand.InterchangeProjectUsageResource(
            resource="pkg:sysand/acme/index-lib", version_constraint=None
        ),
        sysand.InterchangeProjectUsageIndex(
            publisher="Acme Labs", name="Other Lib", version_constraint="^1"
        ),
    ]

    assert _model_roundtrip(usage) == [
        {"resource": "pkg:sysand/acme/index-lib", "version_constraint": None},
        {"publisher": "Acme Labs", "name": "Other Lib", "version_constraint": "^1"},
    ]


def test_an_index_usage_needs_a_constraint() -> None:
    with pytest.raises(Exception):
        _model_roundtrip(
            [{"publisher": "Acme Labs", "name": "Other Lib"}]  # type: ignore[list-item]
        )


def compare_sources(
    sources: Union[List[Path], List[str]],
    expected_sources: Union[List[Path], List[str]],
) -> None:
    assert len(sources) == len(expected_sources)
    for source, expected_source in zip(sources, expected_sources):
        assert os.path.samefile(source, expected_source), (
            f"source: {source}, expected_source: {expected_source}"
        )


def test_end_to_end_install_sources() -> None:
    # A standard library is identified by its hard-coded IRI; the version must
    # match the embedded standard library metadata so that every `Dependencies`
    # mode resolves the same usage.
    std_iri = "https://www.omg.org/spec/KerML/20250201/Function-Library.kpar"
    std_version = "1.0.0"

    with (
        tempfile.TemporaryDirectory() as tmp_main,
        tempfile.TemporaryDirectory() as tmp_dep,
        tempfile.TemporaryDirectory() as tmp_std,
    ):
        tmp_main = Path(tmp_main).resolve()
        tmp_dep = Path(tmp_dep).resolve()
        tmp_std = Path(tmp_std).resolve()
        sysand.init(
            project_dir=tmp_main,
            name="test_end_to_end_install_sources",
            publisher="a",
            version="1.2.3",
        )
        sysand.init(
            project_dir=tmp_dep,
            name="test_end_to_end_install_sources_dep",
            publisher="a",
            version="1.2.3",
        )
        sysand.init(
            project_dir=tmp_std,
            name="Kernel Function Library",
            publisher="a",
            version=std_version,
        )

        with open(Path(tmp_main) / "src.sysml", "w") as f:
            f.write("package Src;")

        sysand.include(project_dir=tmp_main, src_path="src.sysml")

        with open(Path(tmp_dep) / "src_dep.sysml", "w") as f:
            f.write("package SrcDep;")

        sysand.include(project_dir=tmp_dep, src_path="src_dep.sysml")

        with open(Path(tmp_std) / "src_std.sysml", "w") as f:
            f.write("package SrcStd;")

        sysand.include(project_dir=tmp_std, src_path="src_std.sysml")

        env_path = Path(tmp_main) / sysand.env.DEFAULT_ENV_NAME

        sysand.env.env(path=env_path)

        sysand.env.install_path(
            env_path=env_path,
            iri="urn:kpar:test_end_to_end_install_sources_dep",
            location=tmp_dep,
        )
        sysand.env.install_path(env_path=env_path, iri=std_iri, location=tmp_std)

        sysand.add(
            project_dir=tmp_main,
            iri="urn:kpar:test_end_to_end_install_sources_dep",
            version_constraint="1.2.3",
        )
        sysand.add(project_dir=tmp_main, iri=std_iri, version_constraint=std_version)

        dep_src = (
            env_path
            / "lib"
            / "kpar.test_end_to_end_install_sources_dep_1.2.3"
            / "src_dep.sysml"
        )

        [std_src] = (env_path / "lib").glob("*/src_std.sysml")

        # By default only the project's own sources are listed.
        compare_sources(
            sysand.sources(project_dir=tmp_main),
            [str(Path(tmp_main) / "src.sysml")],
        )
        compare_sources(
            sysand.sources(project_dir=tmp_dep),
            [str(Path(tmp_dep) / "src_dep.sysml")],
        )
        # Own sources together with dependency sources, excluding std libs.
        compare_sources(
            sysand.sources(
                project_dir=tmp_main,
                dependencies=sysand.Dependencies.DEPS,
                env_path=env_path,
            ),
            [str(Path(tmp_main) / "src.sysml"), str(dep_src)],
        )
        # Only dependency sources.
        compare_sources(
            sysand.sources(
                project_dir=tmp_main,
                no_own=True,
                dependencies=sysand.Dependencies.DEPS,
                env_path=env_path,
            ),
            [str(dep_src)],
        )
        # no_own without dependencies yields nothing.
        compare_sources(sysand.sources(project_dir=tmp_main, no_own=True), [])

        # DEPS_STD includes both the dependency and the std lib.
        compare_sources(
            sorted(
                sysand.sources(
                    project_dir=tmp_main,
                    no_own=True,
                    dependencies=sysand.Dependencies.DEPS_STD,
                    env_path=env_path,
                ),
                key=lambda p: Path(p).name,
            ),
            sorted([str(dep_src), str(std_src)], key=lambda p: Path(p).name),
        )
        # STD includes only the std lib.
        compare_sources(
            sysand.sources(
                project_dir=tmp_main,
                no_own=True,
                dependencies=sysand.Dependencies.STD,
                env_path=env_path,
            ),
            [str(std_src)],
        )

        sysand.exclude(project_dir=tmp_main, src_path="src.sysml")

        compare_sources(
            sysand.sources(
                project_dir=tmp_main,
                dependencies=sysand.Dependencies.DEPS,
                env_path=env_path,
            ),
            [str(dep_src)],
        )
        compare_sources(
            sysand.sources(
                project_dir=tmp_main,
                no_own=True,
                dependencies=sysand.Dependencies.DEPS,
                env_path=env_path,
            ),
            [str(dep_src)],
        )


def test_root() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        tmpdirname = Path(tmpdirname).resolve()
        sysand.init(
            project_dir=tmpdirname, name="test_root", publisher="a", version="1.2.3"
        )

        subdir = tmpdirname / "sub" / "nested"
        subdir.mkdir(parents=True)

        root_from_top = sysand.root(path=tmpdirname)
        root_from_sub = sysand.root(path=subdir)

        assert root_from_top is not None
        assert root_from_sub is not None
        assert os.path.samefile(root_from_top, tmpdirname)
        assert os.path.samefile(root_from_sub, tmpdirname)


def test_root_not_in_project() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        assert sysand.root(path=tmpdirname) is None


@pytest.mark.parametrize(
    "compression",
    [None, sysand.CompressionMethod.STORED, sysand.CompressionMethod.DEFLATED],
)
def test_build(compression: Union[sysand.CompressionMethod, None]) -> None:
    with tempfile.TemporaryDirectory() as tmp_main:
        tmp_main = Path(tmp_main).resolve()
        sysand.init(
            project_dir=tmp_main, name="test_build", publisher="a", version="1.2.3"
        )

        with open(tmp_main / "src.sysml", "w") as f:
            f.write("package Src;")

        sysand.include(project_dir=tmp_main, src_path="src.sysml")

        sysand.build(
            output_path=tmp_main / "test_build.kpar",
            project_dir=tmp_main,
            compression=compression,
        )
