# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: © 2026 Sysand contributors <opensource@sensmetry.com>

import logging
import tempfile
from pathlib import Path
import re
import os
from typing import List, Union

import pytest
from pytest_httpserver import HTTPServer

import sysand
from mockindex import MockIndex


def test_basic_init(caplog: pytest.LogCaptureFixture) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init("test_basic_init", "a", "1.2.3", tmpdirname)

        assert caplog.record_tuples == [
            (
                "sysand_core.commands.init",
                logging.INFO,
                "    Creating interchange project `test_basic_init`",
            )
        ]
        with open(Path(tmpdirname) / ".project.json", "r") as f:
            assert (
                f.read()
                == '{\n  "name": "test_basic_init",\n  "publisher": "a",\n  "version": "1.2.3"\n}\n'
            )
        with open(Path(tmpdirname) / ".meta.json", "r") as f:
            assert re.match(
                r'\{\n  "index": \{\},\n  "created": "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z"\n}\n',
                f.read(),
            )


def test_basic_env() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        env_path = Path(tmpdirname) / sysand.env.DEFAULT_ENV_NAME
        sysand.env.env(env_path)
        assert env_path.is_dir()
        content = (env_path / "env.toml").read_text()
        assert (
            content
            == '# This file is automatically generated by Sysand and is not intended to be edited manually.\n\nversion = "0.1"\n'
        )


def test_add_accepts_sysand_shorthand() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init("test_add_accepts_sysand_shorthand", "a", "1.2.3", tmpdirname)

        sysand.add(tmpdirname, "acme-labs/my.project")

        assert (
            (Path(tmpdirname) / ".project.json").read_text()
            == '{\n  "name": "test_add_accepts_sysand_shorthand",\n  "publisher": "a",\n  "version": "1.2.3",\n  "usage": [\n    {\n      "resource": "pkg:sysand/acme-labs/my.project"\n    }\n  ]\n}\n'
        )


def test_remove_accepts_sysand_shorthand() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init("test_remove_accepts_sysand_shorthand", "a", "1.2.3", tmpdirname)

        sysand.add(tmpdirname, "acme-labs/my.project")
        sysand.remove(tmpdirname, "acme-labs/my.project")

        assert (
            (Path(tmpdirname) / ".project.json").read_text()
            == '{\n  "name": "test_remove_accepts_sysand_shorthand",\n  "publisher": "a",\n  "version": "1.2.3"\n}\n'
        )


SYSAND_FORMATTED_MANIFEST = """{
  "version": "1.2.3",
  "name": "fidelity",
  "x-unknown-top-level": {
    "kept": true
  },
  "publisher": "acme",
  "usage": [
    {
      "dir": "../local-lib",
      "publisher": "local-pub",
      "name": "local-lib"
    },
    {
      "x-unknown-in-usage": null,
      "resource": "pkg:sysand/mock/library",
      "versionConstraint": ">=0.10.0, <0.11.0"
    }
  ]
}
"""


def _one_line_diff(before: str, after: str) -> tuple[str, str]:
    old_lines = before.splitlines(keepends=True)
    new_lines = after.splitlines(keepends=True)
    assert len(old_lines) == len(new_lines)
    differing = [(o, n) for o, n in zip(old_lines, new_lines) if o != n]
    assert len(differing) == 1, differing
    return differing[0]


def test_set_usage_constraint_preserves_document(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    change = sysand.set_usage_constraint(tmp_path, "mock/library", ">=0.11.0, <0.12.0")

    assert change == {
        "resource": "pkg:sysand/mock/library",
        "found": True,
        "changed": True,
        "old_constraint": ">=0.10.0, <0.11.0",
        "new_constraint": ">=0.11.0, <0.12.0",
    }
    old_line, new_line = _one_line_diff(SYSAND_FORMATTED_MANIFEST, manifest.read_text())
    assert old_line == '      "versionConstraint": ">=0.10.0, <0.11.0"\n'
    assert new_line == '      "versionConstraint": ">=0.11.0, <0.12.0"\n'


def test_set_usage_constraint_purl_matches_shorthand_declaration(
    tmp_path: Path,
) -> None:
    (tmp_path / ".project.json").write_text(SYSAND_FORMATTED_MANIFEST)
    change = sysand.set_usage_constraint(tmp_path, "pkg:sysand/mock/library", "0.11.0")
    assert change["found"] and change["changed"]
    assert change["new_constraint"] == "0.11.0"


def test_set_usage_constraint_clear(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    change = sysand.set_usage_constraint(tmp_path, "mock/library", None)

    assert change["changed"] is True
    assert change["old_constraint"] == ">=0.10.0, <0.11.0"
    assert change["new_constraint"] is None
    expected = SYSAND_FORMATTED_MANIFEST.replace(
        ',\n      "versionConstraint": ">=0.10.0, <0.11.0"', ""
    )
    assert manifest.read_text() == expected

    # Setting a constraint on a usage without one appends it as the last key.
    sysand.set_usage_constraint(tmp_path, "mock/library", "^0.11")
    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST.replace(
        ">=0.10.0, <0.11.0", "^0.11"
    )


def test_set_usage_constraint_unchanged_does_not_touch_file(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)
    os.utime(manifest, ns=(1_000_000_000_000_000_000, 1_000_000_000_000_000_000))
    before = manifest.stat()

    change = sysand.set_usage_constraint(tmp_path, "mock/library", ">=0.10.0, <0.11.0")

    assert change["found"] is True
    assert change["changed"] is False
    assert change["old_constraint"] == change["new_constraint"] == ">=0.10.0, <0.11.0"
    after = manifest.stat()
    assert after.st_mtime_ns == before.st_mtime_ns
    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST


def test_set_usage_constraint_not_found(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.set_usage_constraint(tmp_path, "acme/absent", "1.0.0")
    assert excinfo.value.wrote is False
    assert isinstance(excinfo.value, RuntimeError)
    assert "pkg:sysand/acme/absent" in str(excinfo.value)

    change = sysand.set_usage_constraint(
        tmp_path, "acme/absent", "1.0.0", must_exist=False
    )
    assert change == {
        "resource": "pkg:sysand/acme/absent",
        "found": False,
        "changed": False,
        "old_constraint": None,
        "new_constraint": None,
    }
    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST

    # A missing manifest is an error even with must_exist=False.
    with pytest.raises(sysand.ProjectError):
        sysand.set_usage_constraint(
            tmp_path / "nowhere", "acme/absent", "1.0.0", must_exist=False
        )


def test_set_usage_constraint_rejects_bad_input(tmp_path: Path) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(SYSAND_FORMATTED_MANIFEST)

    with pytest.raises(ValueError):
        sysand.set_usage_constraint(tmp_path, "mock/library", "nonsense")
    with pytest.raises(ValueError):
        sysand.set_usage_constraint(tmp_path, "ab/proj0", "1.0.0")
    assert manifest.read_text() == SYSAND_FORMATTED_MANIFEST

    manifest.write_text(
        SYSAND_FORMATTED_MANIFEST.replace(
            '"dir": "../local-lib"', '"resource": "pkg:sysand/mock/library"'
        )
    )
    with pytest.raises(sysand.ProjectError) as excinfo:
        sysand.set_usage_constraint(tmp_path, "mock/library", "1.0.0")
    assert "2 times" in str(excinfo.value)
    assert excinfo.value.wrote is False


def test_set_usage_constraint_normalizes_hand_formatted_whitespace(
    tmp_path: Path,
) -> None:
    manifest = tmp_path / ".project.json"
    manifest.write_text(
        '{"name":"hand","version":"1.0.0","usage":[{"resource":"a:b","versionConstraint":"1.0.0"}],"z":1}'
    )
    sysand.set_usage_constraint(tmp_path, "a:b", "2.0.0")
    # Same keys, same order, sysand's whitespace.
    assert (
        manifest.read_text()
        == """{
  "name": "hand",
  "version": "1.0.0",
  "usage": [
    {
      "resource": "a:b",
      "versionConstraint": "2.0.0"
    }
  ],
  "z": 1
}
"""
    )


def test_add_returns_whether_a_usage_was_added(tmp_path: Path) -> None:
    sysand.init("test_add_returns", "a", "1.2.3", tmp_path)

    assert sysand.add(tmp_path, "acme-labs/my.project", ">=1.0.0") is True
    assert sysand.add(tmp_path, "acme-labs/my.project", ">=1.0.0") is False
    assert sysand.add(tmp_path, "acme-labs/other") is True


def test_basic_info(caplog: pytest.LogCaptureFixture) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    with tempfile.TemporaryDirectory() as tmpdirname:
        sysand.init("test_basic_info", "a", "1.2.3", tmpdirname)

        info_meta = sysand.info_path(tmpdirname)
        assert info_meta is not None

        info, meta = info_meta

        assert info == {
            "name": "test_basic_info",
            "publisher": "a",
            "description": None,
            "version": "1.2.3",
            "license": None,
            "maintainer": [],
            "website": None,
            "topic": [],
            "usage": [],
        }

        assert meta["index"] == {}
        assert isinstance(meta["created"], str)
        assert re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$", meta["created"])
        assert meta["metamodel"] is None
        assert meta["includes_derived"] is None
        assert meta["includes_implied"] is None
        assert meta["checksum"] is None

        file_uri = Path(tmpdirname).resolve().as_uri()

        info_meta2 = sysand.info(file_uri)
        assert info_meta2 == info_meta


def test_http_info(caplog: pytest.LogCaptureFixture, httpserver: HTTPServer) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    httpserver.expect_request("/.project.json").respond_with_json(
        {"name": "test_http_info", "publisher": "a", "version": "1.2.3"}
    )
    httpserver.expect_request("/.meta.json").respond_with_json(
        {"index": {}, "created": "0000-00-00T00:00:00.123456789Z"}
    )

    info, meta = sysand.info(httpserver.url_for(""))

    assert info == {
        "name": "test_http_info",
        "publisher": "a",
        "description": None,
        "version": "1.2.3",
        "license": None,
        "maintainer": [],
        "website": None,
        "topic": [],
        "usage": [],
    }

    assert meta["index"] == {}
    # meta['created'] utc time
    assert meta["metamodel"] is None
    assert meta["includes_derived"] is None
    assert meta["includes_implied"] is None
    assert meta["checksum"] is None


def test_index_info(caplog: pytest.LogCaptureFixture, mock_index: MockIndex) -> None:
    level = logging.DEBUG
    logging.basicConfig(level=level)
    caplog.set_level(level)

    # Non-PURL IRIs live under `/_iri/<sha256hex>/`; the fixture serves the
    # real index layout, with no discovery document (index_root defaults to
    # the discovery root).
    mock_index.publish("urn:kpar:test_index_info", "1.2.3")

    info, meta = sysand.info("urn:kpar:test_index_info", index_urls=mock_index.url)

    assert info["name"] == "test_index_info"
    assert info["version"] == "1.2.3"
    assert info["usage"] == []
    assert info["publisher"] is None

    assert meta["index"] == {}
    assert isinstance(meta["created"], str)
    assert re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$", meta["created"])
    assert meta["metamodel"] is None
    assert meta["includes_derived"] is None
    assert meta["includes_implied"] is None
    assert meta["checksum"] is None

    iri_dir = "/_iri/19148b59a7f258e6eab15189ebcc5b6f884e02690a3b27f3f43e4c6e15dd9536"
    assert mock_index.requests("*/versions.json") == [f"{iri_dir}/versions.json"]
    assert mock_index.requests("/index.json") == []


def test_model_roundtrip() -> None:
    # Round-trips the typed dicts through the Rust model types
    from sysand._sysand_core import _do_model_roundtrip_py  # type: ignore

    info: sysand.InterchangeProjectInfo = {
        "name": "roundtrip-project",
        "publisher": "acme",
        "description": "A project with every exposed info field",
        "version": "1.2.3",
        "license": "MIT",
        "maintainer": ["Alice", "Bob"],
        "website": "https://example.com/roundtrip",
        "topic": ["sysml", "bindings"],
        "usage": [
            sysand.InterchangeProjectUsageResource(
                resource="pkg:sysand/acme/remote-lib",
                version_constraint=">=1.0.0",
            ),
            sysand.InterchangeProjectUsageDirectory(
                dir="../local-lib", publisher="local-pub", name="local-lib"
            ),
            sysand.InterchangeProjectUsageKparPath(
                kpar_path="deps/archive-lib.kpar",
                publisher="archive-pub",
                name="archive-lib",
            ),
        ],
    }

    metadata: sysand.InterchangeProjectMetadata = {
        "index": {"Alpha": "src/Alpha.sysml", "Beta": "src/nested/Beta.kerml"},
        "created": "2026-01-02T03:04:05Z",
        "metamodel": "https://www.omg.org/spec/SysML/20250201",
        "includes_derived": True,
        "includes_implied": False,
        "checksum": {
            "src/Alpha.sysml": sysand.InterchangeProjectChecksum(
                value="0123456789abcdef", algorithm="MD5"
            ),
            "src/nested/Beta.kerml": sysand.InterchangeProjectChecksum(
                value="deadbeef", algorithm="ADLER32"
            ),
        },
    }

    roundtripped_info, roundtripped_metadata = _do_model_roundtrip_py(info, metadata)

    assert roundtripped_info == info
    assert roundtripped_metadata == metadata


def compare_sources(
    sources: Union[List[Path], List[str]],
    expected_sources: Union[List[Path], List[str]],
) -> None:
    assert len(sources) == len(expected_sources)
    for source, expected_source in zip(sources, expected_sources):
        assert os.path.samefile(source, expected_source), (
            f"source: {source}, expected_source: {expected_source}"
        )


def test_end_to_end_install_sources() -> None:
    # A standard library is identified by its hard-coded IRI; the version must
    # match the embedded standard library metadata so that every `Dependencies`
    # mode resolves the same usage.
    std_iri = "https://www.omg.org/spec/KerML/20250201/Function-Library.kpar"
    std_version = "1.0.0"

    with (
        tempfile.TemporaryDirectory() as tmp_main,
        tempfile.TemporaryDirectory() as tmp_dep,
        tempfile.TemporaryDirectory() as tmp_std,
    ):
        tmp_main = Path(tmp_main).resolve()
        tmp_dep = Path(tmp_dep).resolve()
        tmp_std = Path(tmp_std).resolve()
        sysand.init("test_end_to_end_install_sources", "a", "1.2.3", tmp_main)
        sysand.init("test_end_to_end_install_sources_dep", "a", "1.2.3", tmp_dep)
        sysand.init("Kernel Function Library", "a", std_version, tmp_std)

        with open(Path(tmp_main) / "src.sysml", "w") as f:
            f.write("package Src;")

        sysand.include(tmp_main, "src.sysml")

        with open(Path(tmp_dep) / "src_dep.sysml", "w") as f:
            f.write("package SrcDep;")

        sysand.include(tmp_dep, "src_dep.sysml")

        with open(Path(tmp_std) / "src_std.sysml", "w") as f:
            f.write("package SrcStd;")

        sysand.include(tmp_std, "src_std.sysml")

        env_path = Path(tmp_main) / sysand.env.DEFAULT_ENV_NAME

        sysand.env.env(env_path)

        sysand.env.install_path(
            env_path, "urn:kpar:test_end_to_end_install_sources_dep", tmp_dep
        )
        sysand.env.install_path(env_path, std_iri, tmp_std)

        sysand.add(tmp_main, "urn:kpar:test_end_to_end_install_sources_dep", "1.2.3")
        sysand.add(tmp_main, std_iri, std_version)

        dep_src = (
            env_path
            / "lib"
            / "kpar.test_end_to_end_install_sources_dep_1.2.3"
            / "src_dep.sysml"
        )

        [std_src] = (env_path / "lib").glob("*/src_std.sysml")

        # By default only the project's own sources are listed.
        compare_sources(
            sysand.sources(tmp_main),
            [str(Path(tmp_main) / "src.sysml")],
        )
        compare_sources(
            sysand.sources(tmp_dep),
            [str(Path(tmp_dep) / "src_dep.sysml")],
        )
        # Own sources together with dependency sources, excluding std libs.
        compare_sources(
            sysand.sources(
                tmp_main, dependencies=sysand.Dependencies.DEPS, env_path=env_path
            ),
            [str(Path(tmp_main) / "src.sysml"), str(dep_src)],
        )
        # Only dependency sources.
        compare_sources(
            sysand.sources(
                tmp_main,
                no_own=True,
                dependencies=sysand.Dependencies.DEPS,
                env_path=env_path,
            ),
            [str(dep_src)],
        )
        # no_own without dependencies yields nothing.
        compare_sources(sysand.sources(tmp_main, no_own=True), [])

        # DEPS_STD includes both the dependency and the std lib.
        compare_sources(
            sorted(
                sysand.sources(
                    tmp_main,
                    no_own=True,
                    dependencies=sysand.Dependencies.DEPS_STD,
                    env_path=env_path,
                ),
                key=lambda p: Path(p).name,
            ),
            sorted([str(dep_src), str(std_src)], key=lambda p: Path(p).name),
        )
        # STD includes only the std lib.
        compare_sources(
            sysand.sources(
                tmp_main,
                no_own=True,
                dependencies=sysand.Dependencies.STD,
                env_path=env_path,
            ),
            [str(std_src)],
        )

        sysand.exclude(tmp_main, "src.sysml")

        compare_sources(
            sysand.sources(
                tmp_main, dependencies=sysand.Dependencies.DEPS, env_path=env_path
            ),
            [str(dep_src)],
        )
        compare_sources(
            sysand.sources(
                tmp_main,
                no_own=True,
                dependencies=sysand.Dependencies.DEPS,
                env_path=env_path,
            ),
            [str(dep_src)],
        )


def test_root() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        tmpdirname = Path(tmpdirname).resolve()
        sysand.init("test_root", "a", "1.2.3", tmpdirname)

        subdir = tmpdirname / "sub" / "nested"
        subdir.mkdir(parents=True)

        root_from_top = sysand.root(tmpdirname)
        root_from_sub = sysand.root(subdir)

        assert root_from_top is not None
        assert root_from_sub is not None
        assert os.path.samefile(root_from_top, tmpdirname)
        assert os.path.samefile(root_from_sub, tmpdirname)


def test_root_not_in_project() -> None:
    with tempfile.TemporaryDirectory() as tmpdirname:
        assert sysand.root(tmpdirname) is None


@pytest.mark.parametrize(
    "compression",
    [None, sysand.CompressionMethod.STORED, sysand.CompressionMethod.DEFLATED],
)
def test_build(compression: Union[sysand.CompressionMethod, None]) -> None:
    with tempfile.TemporaryDirectory() as tmp_main:
        tmp_main = Path(tmp_main).resolve()
        sysand.init("test_build", "a", "1.2.3", tmp_main)

        with open(tmp_main / "src.sysml", "w") as f:
            f.write("package Src;")

        sysand.include(tmp_main, "src.sysml")

        sysand.build(
            output_path=tmp_main / "test_build.kpar",
            project_path=tmp_main,
            compression=compression,
        )
