// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: © 2025 Sysand contributors <opensource@sensmetry.com>

use assert_cmd::prelude::*;
use indexmap::IndexMap;
use mockito::Matcher;
use predicates::prelude::*;
use reqwest::header;
use sysand_core::{
    commands::lock::DEFAULT_LOCKFILE_NAME,
    env::{DEFAULT_ENV_NAME, local_directory::METADATA_PATH},
};

// pub due to https://github.com/rust-lang/rust/issues/46379
mod common;
pub use common::*;

#[test]
fn sync_to_current() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, out) = run_sysand(
        ["init", "--version", "1.2.3", "--name", "sync_to_current"],
        None,
    )?;

    std::fs::write(cwd.join("test.sysml"), b"package P;\n")?;

    out.assert().success();

    let out = run_sysand_in(&cwd, ["include", "test.sysml"], None)?;

    out.assert().success();

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("Creating"))
        .stderr(predicate::str::contains("Syncing"));

    let env_path = cwd.join(DEFAULT_ENV_NAME);

    let env_metadata = std::fs::read_to_string(env_path.join(METADATA_PATH))?;

    assert_eq!(
        env_metadata,
        format!(
            r#"# This file is automatically generated by Sysand and is not intended to be edited manually.

version = "0.1"

[[project]]
publisher = "untitled"
name = "sync_to_current"
version = "1.2.3"
path = "."
editable = true
"#
        )
    );

    let entries: Result<Vec<_>, _> = std::fs::read_dir(env_path)?.collect();

    let mut entry_names: Vec<_> = entries?
        .iter()
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();

    entry_names.sort();

    assert_eq!(entry_names, [METADATA_PATH]);

    Ok(())
}

#[test]
fn sync_to_local() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd) = new_temp_cwd()?;

    // Create local project that can be referred to with src_path
    let lib_dir = cwd.join("lib");
    std::fs::create_dir(&lib_dir)?;
    let proj_dir = lib_dir.join("sync_to_local");
    std::fs::create_dir(&proj_dir)?;
    std::fs::write(
        proj_dir.join(".project.json"),
        r#"{
  "name": "sync_to_local",
  "version": "1.2.3"
}
"#,
    )?;
    std::fs::write(
        proj_dir.join(".meta.json"),
        r#"{
  "index": {},
  "created": "2025-06-12T10:48:55.597880Z"
}
"#,
    )?;

    std::fs::write(
        cwd.join(DEFAULT_LOCKFILE_NAME),
        r#"lock_version = "0.5"

[[project]]
name = "sync_to_local"
version = "1.2.3"
identifiers = ["urn:kpar:sync_to_local"]
sources = [
    { src_path = "lib/sync_to_local", checksum = "fd4566669f12f969e04aa970d27659057357d078d00530d442de21d517959f92" },
]
"#,
    )?;

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("Creating"))
        .stderr(predicate::str::contains("Syncing"))
        .stderr(predicate::str::contains("Installing"));

    let env_metadata = std::fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;

    assert_eq!(
        env_metadata,
        format!(
            r#"# This file is automatically generated by Sysand and is not intended to be edited manually.

version = "0.1"

[[project]]
name = "sync_to_local"
version = "1.2.3"
path = "lib/kpar.sync_to_local_1.2.3"
identifiers = [
    "urn:kpar:sync_to_local",
]
src_cksum = "fd4566669f12f969e04aa970d27659057357d078d00530d442de21d517959f92"
"#
        )
    );

    let out = run_sysand_in(&cwd, ["env", "list"], None)?;

    out.assert()
        .success()
        .stdout(predicate::str::contains("`urn:kpar:sync_to_local` 1.2.3"));

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("env is already up to date"));

    Ok(())
}

#[test]
fn sync_to_remote() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd) = new_temp_cwd()?;

    let mut server = mockito::Server::new();

    let info_mock = server
        .mock("GET", "/.project.json")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"name":"sync_to_remote","version":"1.2.3"}"#)
        .expect(2) // TODO: Reduce this to 1 after caching
        .match_request(|r| r.has_header(header::USER_AGENT))
        .create();

    let meta_mock = server
        .mock("GET", "/.meta.json")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"index":{},"created":"0000-00-00T00:00:00.123456789Z"}"#)
        .expect(2) // TODO: Reduce this to 1 after caching
        .match_request(|r| r.has_header(header::USER_AGENT))
        .create();

    std::fs::write(
        cwd.join(DEFAULT_LOCKFILE_NAME),
        format!(
            r#"lock_version = "0.5"

[[project]]
name = "sync_to_remote"
version = "1.2.3"
identifiers = ["urn:kpar:sync_to_remote"]
sources = [
    {{ remote_src = "{}", checksum = "3bd4c3c6b54690d38eeb035e136b667b4307063451b140feb2f49d266f653a26" }},
]
"#,
            &server.url()
        ),
    )?;

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("Creating"))
        .stderr(predicate::str::contains("Syncing"))
        .stderr(predicate::str::contains("Installing"));

    info_mock.assert();
    meta_mock.assert();

    let env_metadata = std::fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;

    assert_eq!(
        env_metadata,
        format!(
            r#"# This file is automatically generated by Sysand and is not intended to be edited manually.

version = "0.1"

[[project]]
name = "sync_to_remote"
version = "1.2.3"
path = "lib/kpar.sync_to_remote_1.2.3"
identifiers = [
    "urn:kpar:sync_to_remote",
]
src_cksum = "3bd4c3c6b54690d38eeb035e136b667b4307063451b140feb2f49d266f653a26"
"#
        )
    );

    let out = run_sysand_in(&cwd, ["env", "list"], None)?;

    out.assert()
        .success()
        .stdout(predicate::str::contains("`urn:kpar:sync_to_remote` 1.2.3"));

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("env is already up to date"));

    Ok(())
}

#[test]
fn sync_to_remote_auth() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd) = new_temp_cwd()?;

    let mut server = mockito::Server::new();

    // Exact counts pin the fetch fan-in so a regression that adds a
    // redundant fetch trips a test rather than passing silently. The
    // unauthenticated 404s come from the first sync's resolution/auth flow.
    let info_mock = server
        .mock("GET", "/.project.json")
        .match_header("authorization", Matcher::Missing)
        .with_status(404)
        .with_header("content-type", "application/json")
        .with_body(r#"{"name":"sync_to_remote","version":"1.2.3"}"#)
        .expect(2) // TODO: Reduce this to 1
        .create();

    let info_mock_auth = server
        .mock("GET", "/.project.json")
        .match_header(
            "authorization",
            Matcher::Exact("Basic dXNlcl8xMjM0OnBhc3NfNDMyMQ==".to_string()),
        )
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"name":"sync_to_remote","version":"1.2.3"}"#)
        .expect(2) // TODO: Reduce this to 1
        .create();

    let meta_mock = server
        .mock("GET", "/.meta.json")
        .match_header("authorization", Matcher::Missing)
        .with_status(404)
        .with_header("content-type", "application/json")
        .with_body(r#"{"index":{},"created":"0000-00-00T00:00:00.123456789Z"}"#)
        .expect(2) // TODO: Reduce this to 1
        .create();

    let meta_mock_auth = server
        .mock("GET", "/.meta.json")
        .match_header(
            "authorization",
            Matcher::Exact("Basic dXNlcl8xMjM0OnBhc3NfNDMyMQ==".to_string()),
        )
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"index":{},"created":"0000-00-00T00:00:00.123456789Z"}"#)
        .expect(2) // TODO: Reduce this to 1
        .create();

    std::fs::write(
        cwd.join(DEFAULT_LOCKFILE_NAME),
        format!(
            r#"lock_version = "0.5"

[[project]]
name = "sync_to_remote"
version = "1.2.3"
identifiers = ["urn:kpar:sync_to_remote"]
sources = [
    {{ remote_src = "{}", checksum = "3bd4c3c6b54690d38eeb035e136b667b4307063451b140feb2f49d266f653a26" }},
]
"#,
            &server.url()
        )
        .as_bytes(),
    )?;

    let out = run_sysand_in_with(
        &cwd,
        ["sync"],
        None,
        &IndexMap::from([
            (
                "SYSAND_CRED_TEST",
                format!("http://{}/**", server.host_with_port()).as_str(),
            ),
            ("SYSAND_CRED_TEST_BASIC_USER", "user_1234"),
            ("SYSAND_CRED_TEST_BASIC_PASS", "pass_4321"),
        ]),
    )?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("Creating"))
        .stderr(predicate::str::contains("Syncing"))
        .stderr(predicate::str::contains("Installing"));

    info_mock.assert();
    info_mock_auth.assert();
    meta_mock.assert();
    meta_mock_auth.assert();

    let out = run_sysand_in(&cwd, ["env", "list"], None)?;

    out.assert()
        .success()
        .stdout(predicate::str::contains("`urn:kpar:sync_to_remote` 1.2.3"));

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("env is already up to date"));

    Ok(())
}

#[test]
fn sync_to_remote_incorrect_auth() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd) = new_temp_cwd()?;

    let mut server = mockito::Server::new();

    // expect(1) for the paths that should fire; expect(0) for the
    // auth paths that must not (credentials don't match this server, so the
    // authenticated retry should never reach the correctly-matched mock).
    let info_mock = server
        .mock("GET", "/.project.json")
        .match_header("authorization", Matcher::Missing)
        .with_status(404)
        .expect(1)
        .create();

    let info_mock_auth = server
        .mock("GET", "/.project.json")
        .match_header(
            "authorization",
            Matcher::Exact("Basic dXNlcl8xMjM0OnBhc3NfNDMyMQ==".to_string()),
        )
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"name":"sync_to_remote","version":"1.2.3"}"#)
        .expect(0)
        .create();

    let meta_mock = server
        .mock("GET", "/.meta.json")
        .match_header("authorization", Matcher::Missing)
        .with_status(404)
        .expect(1)
        .create();

    let meta_mock_auth = server
        .mock("GET", "/.meta.json")
        .match_header(
            "authorization",
            Matcher::Exact("Basic dXNlcl8xMjM0OnBhc3NfNDMyMQ==".to_string()),
        )
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"index":{},"created":"0000-00-00T00:00:00.123456789Z"}"#)
        .expect(0)
        .create();

    std::fs::write(
        cwd.join(DEFAULT_LOCKFILE_NAME),
        format!(
            r#"lock_version = "0.5"

[[project]]
name = "sync_to_remote"
version = "1.2.3"
identifiers = ["urn:kpar:sync_to_remote"]
sources = [
    {{ remote_src = "{}", checksum = "3bd4c3c6b54690d38eeb035e136b667b4307063451b140feb2f49d266f653a26" }},
]
"#,
            &server.url()
        ),
    )?;

    let out = run_sysand_in_with(
        &cwd,
        ["sync"],
        None,
        &IndexMap::from([
            ("SYSAND_CRED_TEST", "http://127.0.0.1:80/**"),
            ("SYSAND_CRED_TEST_BASIC_USER", "user_1234"),
            ("SYSAND_CRED_TEST_BASIC_PASS", "pass_4321"),
        ]),
    )?;

    info_mock.assert();
    info_mock_auth.assert();
    meta_mock.assert();
    meta_mock_auth.assert();

    out.assert().failure();

    Ok(())
}

/// `sync` with a mix of `LocalSrc` (non-editable) and `Editable` deps in the
/// config must: install the non-editable dep into env, register the editable
/// dep in env.toml without copying it, and also register the current project as
/// editable. Re-running sync is idempotent.
#[test]
fn sync_env_toml_with_editable_and_non_editable() -> Result<(), Box<dyn std::error::Error>> {
    // Set up main project with .meta.json (required for sync to lock itself).
    let (_temp_dir, cwd, out) =
        run_sysand(["init", "--version", "1.0.0", "--name", "sync_mixed"], None)?;
    out.assert().success();
    std::fs::write(cwd.join("P.sysml"), "package P;")?;
    run_sysand_in(&cwd, ["include", "P.sysml"], None)?
        .assert()
        .success();

    // Non-editable dep: needs .meta.json so sync can compute its checksum.
    let (_tmp_src, cwd_src, out) = run_sysand(
        ["init", "--version", "2.0.0", "--name", "sync_mixed_src"],
        None,
    )?;
    out.assert().success();
    std::fs::write(cwd_src.join("Q.sysml"), "package Q;")?;
    run_sysand_in(&cwd_src, ["include", "Q.sysml"], None)?
        .assert()
        .success();

    // Editable dep: only .project.json is needed (no install, just reference).
    let (_tmp_editable, cwd_editable, out) = run_sysand(
        [
            "init",
            "--version",
            "3.0.0",
            "--name",
            "sync_mixed_editable",
        ],
        None,
    )?;
    out.assert().success();

    let config_path = cwd.join("sysand.toml");

    // Record sources without re-locking; sync will generate the lockfile.
    run_sysand_in(
        &cwd,
        [
            "add",
            "--no-lock",
            "urn:kpar:sync-mixed-src",
            "--as-local-src",
            cwd_src.as_str(),
        ],
        Some(config_path.as_str()),
    )?
    .assert()
    .success();

    run_sysand_in(
        &cwd,
        [
            "add",
            "--no-lock",
            "urn:kpar:sync-mixed-editable",
            "--as-editable",
            cwd_editable.as_str(),
        ],
        Some(config_path.as_str()),
    )?
    .assert()
    .success();

    // First sync: generates lockfile, creates env, installs non-editable dep.
    run_sysand_in(&cwd, ["sync"], Some(config_path.as_str()))?
        .assert()
        .success()
        .stderr(predicate::str::contains(
            "Installing `urn:kpar:sync-mixed-src`",
        ));

    let env_toml = std::fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;

    // Non-editable dep is installed with a src checksum.
    assert!(
        env_toml.contains("urn:kpar:sync-mixed-src"),
        "non-editable dep missing from env.toml"
    );
    assert!(
        env_toml.contains("src_cksum"),
        "expected src_cksum for non-editable dep"
    );

    // Editable dep is registered but not installed as a directory copy.
    assert!(
        env_toml.contains("urn:kpar:sync-mixed-editable"),
        "editable dep missing from env.toml"
    );
    assert!(
        env_toml.contains("editable = true"),
        "editable dep should have editable = true"
    );

    // Current project is registered as editable too.
    assert!(
        env_toml.contains("sync_mixed"),
        "current project missing from env.toml"
    );

    // Non-editable dep is physically present inside the env.
    assert!(
        cwd.join(DEFAULT_ENV_NAME)
            .join("lib/kpar.sync-mixed-src_2.0.0")
            .is_dir()
    );

    // Editable dep is NOT copied into the env lib directory.
    assert!(
        !cwd.join(DEFAULT_ENV_NAME)
            .join("lib/kpar.sync-mixed-editable_3.0.0")
            .is_dir()
    );

    // Second sync is idempotent.
    let out = run_sysand_in(&cwd, ["sync"], Some(config_path.as_str()))?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("env is already up to date"));

    Ok(())
}
