// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: © 2025 Sysand contributors <opensource@sensmetry.com>

use std::fs;

use assert_cmd::prelude::*;
use indexmap::IndexMap;
use mockito::Matcher;
use predicates::prelude::*;
use reqwest::header;
use sysand_core::{
    commands::lock::DEFAULT_LOCKFILE_NAME,
    env::{
        DEFAULT_ENV_NAME,
        local_directory::{LocalDirectoryEnvironment, METADATA_PATH},
    },
    lock::{Lock, Source},
};

// pub due to https://github.com/rust-lang/rust/issues/46379
mod common;
pub use common::*;

#[test]
fn sync_to_current() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, out) = cli_init_project_basic("d", "sync_to_current", "1.2.3")?;

    fs::write(cwd.join("test.sysml"), b"package P;\n")?;

    out.assert().success();

    let out = run_sysand_in(&cwd, ["include", "test.sysml"], None)?;

    out.assert().success();

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("Creating"))
        .stderr(predicate::str::contains("Syncing"));

    let env_path = cwd.join(DEFAULT_ENV_NAME);

    let env_metadata = fs::read_to_string(env_path.join(METADATA_PATH))?;

    assert_eq!(
        env_metadata,
        format!(
            r#"# This file is automatically generated by Sysand and is not intended to be edited manually.

version = "0.1"

[[project]]
publisher = "d"
name = "sync_to_current"
version = "1.2.3"
path = "."
editable = true
"#
        )
    );

    let entries: Result<Vec<_>, _> = fs::read_dir(env_path)?.collect();

    let mut entry_names: Vec<_> = entries?
        .iter()
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();

    entry_names.sort();

    assert_eq!(entry_names, [METADATA_PATH]);

    Ok(())
}

#[test]
fn repeated_sync_keeps_lockfile_and_env_toml_stable() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, out) = cli_init_project_basic("a", "lock_sync_stable", "1.2.3")?;
    out.assert().success().stdout(predicate::str::is_empty());

    let (_dep_temp_dir, dep_cwd, out) =
        cli_init_project_basic("a", "lock_sync_stable_dep", "2.0.0")?;
    out.assert().success().stdout(predicate::str::is_empty());

    let config_path = cwd.join("sysand.toml");
    let cfg = Some(config_path.as_str());

    run_sysand_in(
        &cwd,
        [
            "add",
            "--no-lock",
            "urn:kpar:lock-sync-stable-dep",
            "--as-editable",
            dep_cwd.as_str(),
        ],
        cfg,
    )?
    .assert()
    .success();

    run_sysand_in(&cwd, ["lock"], cfg)?
        .assert()
        .success()
        .stdout(predicate::str::is_empty());

    let lock_path = cwd.join(DEFAULT_LOCKFILE_NAME);
    let recorded_lockfile = fs::read_to_string(&lock_path)?;

    run_sysand_in(&cwd, ["sync"], cfg)?.assert().success();

    let env_meta_path = cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH);
    let recorded_env_toml = fs::read_to_string(&env_meta_path)?;

    run_sysand_in(&cwd, ["sync"], cfg)?.assert().success();

    assert_eq!(
        fs::read_to_string(&lock_path)?,
        recorded_lockfile,
        "sysand-lock.toml changed after repeated syncs"
    );
    assert_eq!(
        fs::read_to_string(&env_meta_path)?,
        recorded_env_toml,
        ".sysand/env.toml changed after repeated syncs"
    );

    Ok(())
}

#[test]
fn sync_to_local() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd) = new_temp_cwd()?;

    // Create local project that can be referred to with src_path
    let lib_dir = cwd.join("lib");
    fs::create_dir(&lib_dir)?;
    let proj_dir = lib_dir.join("sync_to_local");
    fs::create_dir(&proj_dir)?;
    fs::write(
        proj_dir.join(".project.json"),
        r#"{
  "name": "sync_to_local",
  "version": "1.2.3"
}
"#,
    )?;
    fs::write(
        proj_dir.join(".meta.json"),
        r#"{
  "index": {},
  "created": "2025-06-12T10:48:55.597880Z"
}
"#,
    )?;

    fs::write(
        cwd.join(DEFAULT_LOCKFILE_NAME),
        r#"lock_version = "0.5"

[[project]]
name = "sync_to_local"
version = "1.2.3"
identifiers = ["urn:kpar:sync_to_local"]
sources = [
    { src_path = "lib/sync_to_local", checksum = "fd4566669f12f969e04aa970d27659057357d078d00530d442de21d517959f92" },
]
"#,
    )?;

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("Creating"))
        .stderr(predicate::str::contains("Syncing"))
        .stderr(predicate::str::contains("Installing"));

    let env_metadata = fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;

    assert_eq!(
        env_metadata,
        format!(
            r#"# This file is automatically generated by Sysand and is not intended to be edited manually.

version = "0.1"

[[project]]
name = "sync_to_local"
version = "1.2.3"
path = "lib/kpar.sync_to_local_1.2.3"
identifiers = [
    "urn:kpar:sync_to_local",
]
src_cksum = "fd4566669f12f969e04aa970d27659057357d078d00530d442de21d517959f92"
"#
        )
    );

    let out = run_sysand_in(&cwd, ["env", "list"], None)?;

    out.assert()
        .success()
        .stdout(predicate::str::contains("`urn:kpar:sync_to_local` 1.2.3"));

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("env is already up to date"));

    Ok(())
}

#[test]
fn sync_to_remote() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd) = new_temp_cwd()?;

    let mut server = mockito::Server::new();

    let info_mock = server
        .mock("GET", "/.project.json")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"name":"sync_to_remote","version":"1.2.3"}"#)
        .expect(2) // TODO: Reduce this to 1 after caching
        .match_request(|r| r.has_header(header::USER_AGENT))
        .create();

    let meta_mock = server
        .mock("GET", "/.meta.json")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"index":{},"created":"0000-00-00T00:00:00.123456789Z"}"#)
        .expect(2) // TODO: Reduce this to 1 after caching
        .match_request(|r| r.has_header(header::USER_AGENT))
        .create();

    fs::write(
        cwd.join(DEFAULT_LOCKFILE_NAME),
        format!(
            r#"lock_version = "0.5"

[[project]]
name = "sync_to_remote"
version = "1.2.3"
identifiers = ["urn:kpar:sync_to_remote"]
sources = [
    {{ remote_src = "{}", checksum = "3bd4c3c6b54690d38eeb035e136b667b4307063451b140feb2f49d266f653a26" }},
]
"#,
            server.url()
        ),
    )?;

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("Creating"))
        .stderr(predicate::str::contains("Syncing"))
        .stderr(predicate::str::contains("Installing"));

    info_mock.assert();
    meta_mock.assert();

    let env_metadata = fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;

    assert_eq!(
        env_metadata,
        format!(
            r#"# This file is automatically generated by Sysand and is not intended to be edited manually.

version = "0.1"

[[project]]
name = "sync_to_remote"
version = "1.2.3"
path = "lib/kpar.sync_to_remote_1.2.3"
identifiers = [
    "urn:kpar:sync_to_remote",
]
src_cksum = "3bd4c3c6b54690d38eeb035e136b667b4307063451b140feb2f49d266f653a26"
"#
        )
    );

    let out = run_sysand_in(&cwd, ["env", "list"], None)?;

    out.assert()
        .success()
        .stdout(predicate::str::contains("`urn:kpar:sync_to_remote` 1.2.3"));

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("env is already up to date"));

    Ok(())
}

#[test]
fn sync_to_remote_auth() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd) = new_temp_cwd()?;

    let mut server = mockito::Server::new();

    // Exact counts pin the fetch fan-in so a regression that adds a
    // redundant fetch trips a test rather than passing silently. The
    // unauthenticated 404s come from the first sync's resolution/auth flow.
    let info_mock = server
        .mock("GET", "/.project.json")
        .match_header("authorization", Matcher::Missing)
        .with_status(404)
        .with_header("content-type", "application/json")
        .with_body(r#"{"name":"sync_to_remote","version":"1.2.3"}"#)
        .expect(2) // TODO: Reduce this to 1
        .create();

    let info_mock_auth = server
        .mock("GET", "/.project.json")
        .match_header(
            "authorization",
            Matcher::Exact("Basic dXNlcl8xMjM0OnBhc3NfNDMyMQ==".to_owned()),
        )
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"name":"sync_to_remote","version":"1.2.3"}"#)
        .expect(2) // TODO: Reduce this to 1
        .create();

    let meta_mock = server
        .mock("GET", "/.meta.json")
        .match_header("authorization", Matcher::Missing)
        .with_status(404)
        .with_header("content-type", "application/json")
        .with_body(r#"{"index":{},"created":"0000-00-00T00:00:00.123456789Z"}"#)
        .expect(2) // TODO: Reduce this to 1
        .create();

    let meta_mock_auth = server
        .mock("GET", "/.meta.json")
        .match_header(
            "authorization",
            Matcher::Exact("Basic dXNlcl8xMjM0OnBhc3NfNDMyMQ==".to_owned()),
        )
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"index":{},"created":"0000-00-00T00:00:00.123456789Z"}"#)
        .expect(2) // TODO: Reduce this to 1
        .create();

    fs::write(
        cwd.join(DEFAULT_LOCKFILE_NAME),
        format!(
            r#"lock_version = "0.5"

[[project]]
name = "sync_to_remote"
version = "1.2.3"
identifiers = ["urn:kpar:sync_to_remote"]
sources = [
    {{ remote_src = "{}", checksum = "3bd4c3c6b54690d38eeb035e136b667b4307063451b140feb2f49d266f653a26" }},
]
"#,
            server.url()
        )
        .as_bytes(),
    )?;

    let out = run_sysand_in_with(
        &cwd,
        ["sync"],
        None,
        &IndexMap::from([
            (
                "SYSAND_CRED_TEST",
                format!("http://{}/**", server.host_with_port()).as_str(),
            ),
            ("SYSAND_CRED_TEST_BASIC_USER", "user_1234"),
            ("SYSAND_CRED_TEST_BASIC_PASS", "pass_4321"),
        ]),
    )?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("Creating"))
        .stderr(predicate::str::contains("Syncing"))
        .stderr(predicate::str::contains("Installing"));

    info_mock.assert();
    info_mock_auth.assert();
    meta_mock.assert();
    meta_mock_auth.assert();

    let out = run_sysand_in(&cwd, ["env", "list"], None)?;

    out.assert()
        .success()
        .stdout(predicate::str::contains("`urn:kpar:sync_to_remote` 1.2.3"));

    let out = run_sysand_in(&cwd, ["sync"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("env is already up to date"));

    Ok(())
}

#[test]
fn sync_to_remote_incorrect_auth() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd) = new_temp_cwd()?;

    let mut server = mockito::Server::new();

    // expect(1) for the paths that should fire; expect(0) for the
    // auth paths that must not (credentials don't match this server, so the
    // authenticated retry should never reach the correctly-matched mock).
    let info_mock = server
        .mock("GET", "/.project.json")
        .match_header("authorization", Matcher::Missing)
        .with_status(404)
        .expect(1)
        .create();

    let info_mock_auth = server
        .mock("GET", "/.project.json")
        .match_header(
            "authorization",
            Matcher::Exact("Basic dXNlcl8xMjM0OnBhc3NfNDMyMQ==".to_owned()),
        )
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"name":"sync_to_remote","version":"1.2.3"}"#)
        .expect(0)
        .create();

    let meta_mock = server
        .mock("GET", "/.meta.json")
        .match_header("authorization", Matcher::Missing)
        .with_status(404)
        .expect(1)
        .create();

    let meta_mock_auth = server
        .mock("GET", "/.meta.json")
        .match_header(
            "authorization",
            Matcher::Exact("Basic dXNlcl8xMjM0OnBhc3NfNDMyMQ==".to_owned()),
        )
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{"index":{},"created":"0000-00-00T00:00:00.123456789Z"}"#)
        .expect(0)
        .create();

    fs::write(
        cwd.join(DEFAULT_LOCKFILE_NAME),
        format!(
            r#"lock_version = "0.5"

[[project]]
name = "sync_to_remote"
version = "1.2.3"
identifiers = ["urn:kpar:sync_to_remote"]
sources = [
    {{ remote_src = "{}", checksum = "3bd4c3c6b54690d38eeb035e136b667b4307063451b140feb2f49d266f653a26" }},
]
"#,
            server.url()
        ),
    )?;

    let out = run_sysand_in_with(
        &cwd,
        ["sync"],
        None,
        &IndexMap::from([
            ("SYSAND_CRED_TEST", "http://127.0.0.1:80/**"),
            ("SYSAND_CRED_TEST_BASIC_USER", "user_1234"),
            ("SYSAND_CRED_TEST_BASIC_PASS", "pass_4321"),
        ]),
    )?;

    info_mock.assert();
    info_mock_auth.assert();
    meta_mock.assert();
    meta_mock_auth.assert();

    out.assert().failure();

    Ok(())
}

/// `sync` with a mix of `LocalSrc` (non-editable) and `Editable` deps in the
/// config must: install the non-editable dep into env, register the editable
/// dep in env.toml without copying it, and also register the current project as
/// editable. Re-running sync is idempotent.
#[test]
fn sync_env_toml_with_editable_and_non_editable() -> Result<(), Box<dyn std::error::Error>> {
    // Set up main project with .meta.json (required for sync to lock itself).
    let (_temp_dir, cwd, out) = cli_init_project_basic("a", "sync_mixed", "1.0.0")?;
    out.assert().success();
    fs::write(cwd.join("P.sysml"), "package P;")?;
    run_sysand_in(&cwd, ["include", "P.sysml"], None)?
        .assert()
        .success();

    // Non-editable dep: needs .meta.json so sync can compute its checksum.
    let (_tmp_src, cwd_src, out) = cli_init_project_basic("a", "sync_mixed_src", "2.0.0")?;
    out.assert().success();
    fs::write(cwd_src.join("Q.sysml"), "package Q;")?;
    run_sysand_in(&cwd_src, ["include", "Q.sysml"], None)?
        .assert()
        .success();

    // Editable dep: only .project.json is needed (no install, just reference).
    let (_tmp_editable, cwd_editable, out) =
        cli_init_project_basic("a", "sync_mixed_editable", "3.0.0")?;
    out.assert().success();

    let config_path = cwd.join("sysand.toml");

    // Record sources without re-locking; sync will generate the lockfile.
    run_sysand_in(
        &cwd,
        [
            "add",
            "--no-lock",
            "urn:kpar:sync-mixed-src",
            "--as-local-src",
            cwd_src.as_str(),
        ],
        Some(config_path.as_str()),
    )?
    .assert()
    .success();

    run_sysand_in(
        &cwd,
        [
            "add",
            "--no-lock",
            "urn:kpar:sync-mixed-editable",
            "--as-editable",
            cwd_editable.as_str(),
        ],
        Some(config_path.as_str()),
    )?
    .assert()
    .success();

    // First sync: generates lockfile, creates env, installs non-editable dep.
    run_sysand_in(&cwd, ["sync"], Some(config_path.as_str()))?
        .assert()
        .success()
        .stderr(predicate::str::contains(
            "Installing `urn:kpar:sync-mixed-src`",
        ));

    let env_toml = fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;

    // Non-editable dep is installed with a src checksum.
    assert!(
        env_toml.contains("urn:kpar:sync-mixed-src"),
        "non-editable dep missing from env.toml"
    );
    assert!(
        env_toml.contains("src_cksum"),
        "expected src_cksum for non-editable dep"
    );

    // Editable dep is registered but not installed as a directory copy.
    assert!(
        env_toml.contains("urn:kpar:sync-mixed-editable"),
        "editable dep missing from env.toml"
    );
    assert!(
        env_toml.contains("editable = true"),
        "editable dep should have editable = true"
    );

    // Current project is registered as editable too.
    assert!(
        env_toml.contains("sync_mixed"),
        "current project missing from env.toml"
    );

    // Non-editable dep is physically present inside the env.
    assert!(
        cwd.join(DEFAULT_ENV_NAME)
            .join("lib/kpar.sync-mixed-src_2.0.0")
            .is_dir()
    );

    // Editable dep is NOT copied into the env lib directory.
    assert!(
        !cwd.join(DEFAULT_ENV_NAME)
            .join("lib/kpar.sync-mixed-editable_3.0.0")
            .is_dir()
    );

    // Second sync is idempotent.
    let out = run_sysand_in(&cwd, ["sync"], Some(config_path.as_str()))?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("env is already up to date"));

    Ok(())
}

/// A transitive `kpar_path` usage must resolve relative to the directory of
/// the project that declares it, not relative to the top-level project being
/// synced
#[test]
fn sync_kpar_path_usage_transitive() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, out) = cli_init_project_basic("a", "app", "1.2.3")?;
    out.assert().success().stdout(predicate::str::is_empty());

    let deps_dir = cwd.join("deps");
    std::fs::create_dir_all(&deps_dir)?;

    // `gadget`: a leaf KPAR, built elsewhere and placed at `deps/gadget.kpar`.
    let gadget_src = cwd.join("gadget_src");
    std::fs::create_dir_all(&gadget_src)?;
    cli_init_project_in(&gadget_src, None, "c", Some("gadget"), Some("2.0.0"), None)?
        .assert()
        .success();
    run_sysand_in(&gadget_src, ["build", "../deps/gadget.kpar"], None)?
        .assert()
        .success();

    // `widget`: a source directory declaring `../gadget.kpar`, resolved (and
    // stored) relative to `widget`'s own directory.
    let widget_dir = deps_dir.join("widget");
    std::fs::create_dir_all(&widget_dir)?;
    cli_init_project_in(&widget_dir, None, "b", Some("widget"), Some("1.0.0"), None)?
        .assert()
        .success();
    run_sysand_in(
        &widget_dir,
        [
            "experimental",
            "add",
            "--no-lock",
            "--kpar-path",
            "../gadget.kpar",
        ],
        None,
    )?
    .assert()
    .success();

    run_sysand_in(
        &cwd,
        ["experimental", "add", "--no-lock", "--dir", "deps/widget"],
        None,
    )?
    .assert()
    .success();

    let out = run_sysand_in(&cwd, ["lock"], None)?;
    out.assert().success();

    let lock_file: Lock =
        toml::from_str(&std::fs::read_to_string(cwd.join(DEFAULT_LOCKFILE_NAME))?)?;
    let projects = lock_file.projects;

    assert_eq!(
        projects.len(),
        3,
        "expected app, widget and gadget in the lockfile, got: {projects:#?}"
    );

    // Resolved paths are relativized back against the top-level project
    // root when recorded in the lockfile.
    let widget = projects
        .iter()
        .find(|p| p.name == "widget")
        .unwrap_or_else(|| panic!("`widget` missing from lockfile: {projects:#?}"));
    assert_eq!(widget.version, "1.0.0");
    let [Source::LocalSrc { src_path, .. }] = widget.sources.as_slice() else {
        panic!("expected a single local src source for `widget`, got: {widget:#?}");
    };
    assert_eq!(src_path.as_str(), "deps/widget");

    let gadget = projects
        .iter()
        .find(|p| p.name == "gadget")
        .unwrap_or_else(|| panic!("`gadget` missing from lockfile: {projects:#?}"));
    assert_eq!(gadget.version, "2.0.0");
    let [Source::LocalKpar { kpar_path, .. }] = gadget.sources.as_slice() else {
        panic!("expected a single local kpar source for `gadget`, got: {gadget:#?}");
    };
    assert_eq!(kpar_path.as_str(), "deps/gadget.kpar");

    let out = run_sysand_in(&cwd, ["sync"], None)?;
    out.assert().success();

    let env_projects = LocalDirectoryEnvironment::read(cwd.join(DEFAULT_ENV_NAME))?
        .projects()
        .to_vec();

    for (name, version) in [("widget", "1.0.0"), ("gadget", "2.0.0")] {
        assert!(
            env_projects
                .iter()
                .any(|p| p.name == name && p.version == version),
            "`{name}` {version} missing from synced env: {env_projects:#?}"
        );
    }

    Ok(())
}

/// `sync` must remove a project from `.sysand` once it is no longer present
/// in the lockfile, while leaving dependencies that are still needed alone.
#[test]
fn sync_prunes_unneeded_dependency_by_default() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, out) = cli_init_project_basic("a", "prune_app", "1.0.0")?;
    out.assert().success();
    fs::write(cwd.join("App.sysml"), "package App;")?;
    run_sysand_in(&cwd, ["include", "App.sysml"], None)?
        .assert()
        .success();

    let (_tmp_keep, cwd_keep, out) = cli_init_project_basic("a", "prune_dep_keep", "1.0.0")?;
    out.assert().success();
    fs::write(cwd_keep.join("Keep.sysml"), "package Keep;")?;
    run_sysand_in(&cwd_keep, ["include", "Keep.sysml"], None)?
        .assert()
        .success();

    let (_tmp_drop, cwd_drop, out) = cli_init_project_basic("a", "prune_dep_drop", "1.0.0")?;
    out.assert().success();
    fs::write(cwd_drop.join("Drop.sysml"), "package Drop;")?;
    run_sysand_in(&cwd_drop, ["include", "Drop.sysml"], None)?
        .assert()
        .success();

    let config_path = cwd.join("sysand.toml");
    let cfg = Some(config_path.as_str());

    run_sysand_in(
        &cwd,
        [
            "add",
            "--no-lock",
            "urn:kpar:prune-dep-keep",
            "--as-local-src",
            cwd_keep.as_str(),
        ],
        cfg,
    )?
    .assert()
    .success();

    run_sysand_in(
        &cwd,
        [
            "add",
            "--no-lock",
            "urn:kpar:prune-dep-drop",
            "--as-local-src",
            cwd_drop.as_str(),
        ],
        cfg,
    )?
    .assert()
    .success();

    run_sysand_in(&cwd, ["lock"], cfg)?.assert().success();
    run_sysand_in(&cwd, ["sync"], cfg)?.assert().success();

    let env_lib = cwd.join(DEFAULT_ENV_NAME).join("lib");
    assert!(env_lib.join("kpar.prune-dep-keep_1.0.0").is_dir());
    assert!(env_lib.join("kpar.prune-dep-drop_1.0.0").is_dir());

    // Drop the usage and regenerate the lockfile without touching the env:
    // `.sysand` still has `prune-dep-drop` installed, but the lockfile no
    // longer lists it.
    run_sysand_in(
        &cwd,
        ["remove", "--no-lock", "urn:kpar:prune-dep-drop"],
        cfg,
    )?
    .assert()
    .success();
    run_sysand_in(&cwd, ["lock"], cfg)?.assert().success();

    let lockfile = fs::read_to_string(cwd.join(DEFAULT_LOCKFILE_NAME))?;
    assert!(
        !lockfile.contains("prune-dep-drop"),
        "expected relocked lockfile to no longer reference `prune-dep-drop`: {lockfile}"
    );

    // Default `sync` prunes the now-unneeded dependency from `.sysand`.
    run_sysand_in(&cwd, ["sync"], cfg)?.assert().success();

    assert!(
        env_lib.join("kpar.prune-dep-keep_1.0.0").is_dir(),
        "still-needed dependency must not be pruned"
    );
    assert!(
        !env_lib.join("kpar.prune-dep-drop_1.0.0").exists(),
        "unneeded dependency must be pruned from `.sysand` by default"
    );

    let env_toml = fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;
    assert!(env_toml.contains("prune-dep-keep"));
    assert!(!env_toml.contains("prune-dep-drop"));

    // Pruning is idempotent.
    run_sysand_in(&cwd, ["sync"], cfg)?
        .assert()
        .success()
        .stderr(predicate::str::contains("env is already up to date"));

    Ok(())
}

/// `sync --no-prune` must leave a dependency that is no longer present in
/// the lockfile installed in `.sysand`.
#[test]
fn sync_no_prune_keeps_unneeded_dependency() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, out) = cli_init_project_basic("a", "no_prune_app", "1.0.0")?;
    out.assert().success();
    fs::write(cwd.join("App.sysml"), "package App;")?;
    run_sysand_in(&cwd, ["include", "App.sysml"], None)?
        .assert()
        .success();

    let (_tmp_keep, cwd_keep, out) = cli_init_project_basic("a", "no_prune_dep_keep", "1.0.0")?;
    out.assert().success();
    fs::write(cwd_keep.join("Keep.sysml"), "package Keep;")?;
    run_sysand_in(&cwd_keep, ["include", "Keep.sysml"], None)?
        .assert()
        .success();

    let (_tmp_drop, cwd_drop, out) = cli_init_project_basic("a", "no_prune_dep_drop", "1.0.0")?;
    out.assert().success();
    fs::write(cwd_drop.join("Drop.sysml"), "package Drop;")?;
    run_sysand_in(&cwd_drop, ["include", "Drop.sysml"], None)?
        .assert()
        .success();

    let config_path = cwd.join("sysand.toml");
    let cfg = Some(config_path.as_str());

    run_sysand_in(
        &cwd,
        [
            "add",
            "--no-lock",
            "urn:kpar:no-prune-dep-keep",
            "--as-local-src",
            cwd_keep.as_str(),
        ],
        cfg,
    )?
    .assert()
    .success();

    run_sysand_in(
        &cwd,
        [
            "add",
            "--no-lock",
            "urn:kpar:no-prune-dep-drop",
            "--as-local-src",
            cwd_drop.as_str(),
        ],
        cfg,
    )?
    .assert()
    .success();

    run_sysand_in(&cwd, ["lock"], cfg)?.assert().success();
    run_sysand_in(&cwd, ["sync"], cfg)?.assert().success();

    let env_lib = cwd.join(DEFAULT_ENV_NAME).join("lib");
    assert!(env_lib.join("kpar.no-prune-dep-keep_1.0.0").is_dir());
    assert!(env_lib.join("kpar.no-prune-dep-drop_1.0.0").is_dir());

    run_sysand_in(
        &cwd,
        ["remove", "--no-lock", "urn:kpar:no-prune-dep-drop"],
        cfg,
    )?
    .assert()
    .success();
    run_sysand_in(&cwd, ["lock"], cfg)?.assert().success();

    let lockfile = fs::read_to_string(cwd.join(DEFAULT_LOCKFILE_NAME))?;
    assert!(!lockfile.contains("no-prune-dep-drop"));

    // `--no-prune` must not remove the now-unneeded dependency from `.sysand`.
    run_sysand_in(&cwd, ["sync", "--no-prune"], cfg)?
        .assert()
        .success();

    assert!(env_lib.join("kpar.no-prune-dep-keep_1.0.0").is_dir());
    assert!(
        env_lib.join("kpar.no-prune-dep-drop_1.0.0").is_dir(),
        "`--no-prune` must leave the unneeded dependency installed in `.sysand`"
    );

    let env_toml = fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;
    assert!(env_toml.contains("no-prune-dep-keep"));
    assert!(
        env_toml.contains("no-prune-dep-drop"),
        "`--no-prune` must leave the unneeded dependency registered in env.toml"
    );

    Ok(())
}
