// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: © 2025 Sysand contributors <opensource@sensmetry.com>

use std::path::Path;

use assert_cmd::prelude::*;
use predicates::prelude::*;
use sysand_core::env::{DEFAULT_ENV_NAME, local_directory::METADATA_PATH};
// Only used by the `env install`/`env uninstall` tests commented out below.
// use camino::Utf8Path;
// use mockito::Server;
// use sysand_core::{project::utils::relativize_path, utils::sha256_lowercase_hex};

// pub due to https://github.com/rust-lang/rust/issues/46379
mod common;
pub use common::*;

/// sysand env should create an empty local environment in
/// ./.sysand, containing only `env.toml` file without any projects
#[test]
fn env_init_empty_env() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, out) = run_sysand(["env"], None)?;

    out.assert().success().stdout(predicate::str::is_empty());

    let env_path = Path::new(DEFAULT_ENV_NAME);

    for entry in std::fs::read_dir(&cwd)? {
        let path = entry?.path();
        assert!(path.is_dir());
        assert_eq!(path.strip_prefix(&cwd)?, env_path);
    }

    assert_eq!(
        std::fs::File::open(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?
            .metadata()?
            .len(),
        DEFAULT_ENV_FILE_CONTENTS.len() as u64
    );

    Ok(())
}

// The `env install`/`env uninstall` subcommands are commented out (see `EnvCommand` in cli.rs).
// Installing a local-src project on `add` and removing it again on `remove` is already covered
// by `add_and_remove_as_local_src` and `remove_keeps_lockfile_valid_and_syncs` in
// `cli_add_remove.rs`, so this test is commented out to match rather than ported to `add`/`remove`.
/*
/// `sysand env install <IRI> --location <LOCATION>` should install the
/// interchange project at <LOCATION> as <IRI> in local env, `sysand env
/// list` should print the <IRI> and version to stdout and `sysand env
/// uninstall <IRI>` should remove it from the env
#[test]
fn env_install_from_local_dir() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    let test_path = fixture_path("test_lib");

    let env_path = Utf8Path::new(DEFAULT_ENV_NAME);

    let out = run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:test",
            "--path",
            test_path.as_str(),
        ],
        None,
    )?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("`urn:kpar:test` 0.0.1"));

    assert_eq!(
        std::fs::read_to_string(cwd.join(env_path).join(METADATA_PATH))?,
        r#"# This file is automatically generated by Sysand and is not intended to be edited manually.

version = "0.1"

[[project]]
name = "Lib test"
version = "0.0.1"
path = "lib/kpar.test_0.0.1"
identifiers = [
    "urn:kpar:test",
]
src_cksum = "c83ef78e3b8d52d622dea6db2e7c6c326801500ae1e99f6a54c39a1f473367b3"
"#
    );

    let project_dir = "lib/kpar.test_0.0.1";

    assert!(cwd.join(env_path).join(project_dir).is_dir());

    assert!(cwd.join(env_path).join(project_dir).is_dir());

    assert!(
        cwd.join(env_path)
            .join(project_dir)
            .join(".project.json")
            .is_file()
    );

    assert!(
        cwd.join(env_path)
            .join(project_dir)
            .join(".meta.json")
            .is_file()
    );

    let out = run_sysand_in(&cwd, ["env", "list"], None)?;

    out.assert()
        .success()
        .stdout(predicate::str::contains("`urn:kpar:test` 0.0.1"));

    let out = run_sysand_in(&cwd, ["env", "uninstall", "urn:kpar:test"], None)?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("urn:kpar:test"));

    let entries = std::fs::read_dir(cwd.join(env_path))?.collect::<Result<Vec<_>, _>>()?;

    let mut entry_names: Vec<_> = entries
        .iter()
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();

    let metadata_path_index = entry_names.iter().position(|e| e == METADATA_PATH).unwrap();

    entry_names.sort();

    assert_eq!(entry_names, [METADATA_PATH, "lib"]);

    assert_eq!(
        std::fs::read_to_string(entries[metadata_path_index].path())?,
        DEFAULT_ENV_FILE_CONTENTS
    );

    Ok(())
}
*/

// The `env uninstall` subcommand is commented out (see `EnvCommand` in cli.rs); it produces an
// env-level "not found" error that `remove` (which errors at the usage level instead) does not
// have an equivalent for, so these tests are commented out to match until that functionality is
// decided on.
/*
/// `sysand env uninstall <IRI>` for an IRI that is not installed in the
/// env should fail with an error, and must not modify `env.toml`
#[test]
fn env_uninstall_nonexistent() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    let env_path = Utf8Path::new(DEFAULT_ENV_NAME);
    let env_toml_before = std::fs::read_to_string(cwd.join(env_path).join(METADATA_PATH))?;

    let out = run_sysand_in(&cwd, ["env", "uninstall", "urn:kpar:missing"], None)?;

    out.assert().failure().stderr(predicate::str::contains(
        "project `urn:kpar:missing` not found in env",
    ));

    assert_eq!(
        std::fs::read_to_string(cwd.join(env_path).join(METADATA_PATH))?,
        env_toml_before
    );

    Ok(())
}

/// `sysand env uninstall <IRI> <VERSION>` for a version that is not
/// installed in the env should fail with an error, even if other versions
/// of the same project are installed
#[test]
fn env_uninstall_nonexistent_version() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    let test_path = fixture_path("test_lib");

    let out = run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:test",
            "--path",
            test_path.as_str(),
        ],
        None,
    )?;
    out.assert().success();

    let out = run_sysand_in(&cwd, ["env", "uninstall", "urn:kpar:test", "9.9.9"], None)?;

    out.assert().failure().stderr(predicate::str::contains(
        "project `urn:kpar:test` not found in env",
    ));

    // The installed version is unaffected
    let out = run_sysand_in(&cwd, ["env", "list"], None)?;
    out.assert()
        .success()
        .stdout(predicate::str::contains("`urn:kpar:test` 0.0.1"));

    Ok(())
}
*/

// The `env install` subcommand is commented out (see `EnvCommand` in cli.rs); installing a
// project from an HTTP kpar URL is covered through `add` by `add_from_http_kpar` in
// `cli_add_remove.rs`, so this test is commented out to match.
/*
#[test]
fn env_install_from_http_kpar() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    let test_path = fixture_path("test_lib.kpar");

    let env_path = Utf8Path::new(DEFAULT_ENV_NAME);

    let mut server = Server::new();

    let test_body = std::fs::read(test_path)?;

    let git_mock = server
        .mock("GET", "/test_lib.kpar/info/refs?service=git-upload-pack")
        .with_status(404)
        .expect(1)
        .create();

    let project_mock = server
        .mock("HEAD", "/test_lib.kpar/.project.json")
        .with_status(404)
        .expect(1)
        .create();

    let meta_mock = server
        .mock("HEAD", "/test_lib.kpar/.meta.json")
        .with_status(404)
        .expect(1)
        .create();

    let head_mock = server
        .mock("HEAD", "/test_lib.kpar")
        .with_status(200)
        .with_header("content-type", "application/octet-stream")
        .with_body(&test_body)
        .expect(0)
        .create();

    let get_mock = server
        .mock("GET", "/test_lib.kpar")
        .with_status(200)
        .with_header("content-type", "application/octet-stream")
        .with_body(&test_body)
        .expect(2) // TODO: Reduce this to 1 after caching
        .create();

    let project_url = format!("{}/test_lib.kpar", server.url());

    let out = run_sysand_in(&cwd, ["env", "install", &project_url], None)?;

    head_mock.assert();
    get_mock.assert();
    git_mock.assert();
    project_mock.assert();
    meta_mock.assert();

    out.assert().success();

    assert_eq!(
        std::fs::read_to_string(cwd.join(env_path).join(METADATA_PATH))?,
        format!(
            r#"# This file is automatically generated by Sysand and is not intended to be edited manually.

version = "0.1"

[[project]]
name = "Lib test"
version = "0.0.1"
path = "lib/127.0.0.1-test_lib_0.0.1"
identifiers = [
    "{}/test_lib.kpar",
]
kpar_cksum = "1838ad10a9c1fa46c74a92c68212e6fdcf6f6011a94ca5f16e343ea18a8e203b"
"#,
            server.url()
        )
    );

    Ok(())
}
*/

// The `env install`/`env uninstall` subcommands are commented out (see `EnvCommand` in cli.rs);
// `--allow-overwrite` and `--allow-multiple` have no equivalent through `add`/`sync`, so these
// tests are commented out to match until that functionality is decided on.
/*
/// `sysand env install <IRI> --location <LOCATION>` should install
/// the interchange project att <LOCATION> as <IRI> in local env.
/// If the same command is run again it should give an error,
/// and if run again with flag `--allow-overwrite` it should succeed
#[test]
fn env_install_from_local_dir_allow_overwrite() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    let test_path = fixture_path("test_lib");

    let out = run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:test",
            "--path",
            test_path.as_str(),
        ],
        None,
    )?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("`urn:kpar:test` 0.0.1"));

    let out = run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:test",
            "--path",
            test_path.as_str(),
        ],
        None,
    )?;

    out.assert()
        .failure()
        .stderr(predicate::str::contains("error"));

    let out = run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:test",
            "--path",
            test_path.as_str(),
            "--allow-overwrite",
        ],
        None,
    )?;

    out.assert()
        .success()
        .stderr(predicate::str::contains("`urn:kpar:test` 0.0.1"));

    Ok(())
}
*/

#[test]
fn install_nonexistent() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, out) = cli_init_project_basic("a", "install_nonexistent", "1.2.3")?;

    out.assert().success();

    let out = run_sysand_in(
        &cwd,
        ["add", "urn:kpar:install_nonexistent", "--no-index"],
        None,
    )?;

    out.assert().failure().stderr(predicate::str::contains(
        "no resolver was able to resolve the project",
    ));

    Ok(())
}

// The `env install` subcommand is commented out (see `EnvCommand` in cli.rs); `--allow-multiple`
// has no equivalent through `add`/`sync` (the solver picks a single version to satisfy all
// usages), so this test is commented out to match until that functionality is decided on.
/*
/// `--allow-multiple` lets a different version of an already-installed project
/// be installed alongside it; the same version still triggers an error.
/// `env list` then names each installed version once.
#[test]
fn env_install_allow_multiple() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    // Build v1 with a .meta.json so checksum_canonical_variant succeeds.
    let (_temp_v1, cwd_v1, out) = cli_init_project_basic("a", "allow_multiple_lib", "1.0.0")?;
    out.assert().success();
    std::fs::write(cwd_v1.join("TestLib.sysml"), "package TestLib;")?;
    run_sysand_in(&cwd_v1, ["include", "TestLib.sysml"], None)?
        .assert()
        .success();

    // Build v2 with the same IRI but a different version.
    let (_temp_v2, cwd_v2, out) = cli_init_project_basic("a", "allow_multiple_lib", "2.0.0")?;
    out.assert().success();
    std::fs::write(cwd_v2.join("TestLib.sysml"), "package TestLib;")?;
    run_sysand_in(&cwd_v2, ["include", "TestLib.sysml"], None)?
        .assert()
        .success();

    // Install v1.
    run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:allow-multiple-lib",
            "--path",
            cwd_v1.as_str(),
        ],
        None,
    )?
    .assert()
    .success();

    // Without --allow-multiple, installing v2 (a different version) fails.
    run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:allow-multiple-lib",
            "--path",
            cwd_v2.as_str(),
        ],
        None,
    )?
    .assert()
    .failure()
    .stderr(predicate::str::contains(
        "project with IRI `urn:kpar:allow-multiple-lib` is already installed",
    ));

    // With --allow-multiple, installing v2 alongside v1 succeeds.
    run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:allow-multiple-lib",
            "--path",
            cwd_v2.as_str(),
            "--allow-multiple",
        ],
        None,
    )?
    .assert()
    .success()
    .stderr(predicate::str::contains(
        "`urn:kpar:allow-multiple-lib` 2.0.0",
    ));

    // --allow-multiple still rejects reinstalling the same version that is
    // already present (that requires --allow-overwrite instead).
    run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:allow-multiple-lib",
            "--path",
            cwd_v1.as_str(),
            "--allow-multiple",
        ],
        None,
    )?
    .assert()
    .failure()
    .stderr(predicate::str::contains(
        "project with IRI `urn:kpar:allow-multiple-lib` already has version `1.0.0` installed",
    ));

    // The project is listed once per installed version
    run_sysand_in(&cwd, ["env", "list"], None)?
        .assert()
        .success()
        .stdout("`urn:kpar:allow-multiple-lib` 1.0.0\n`urn:kpar:allow-multiple-lib` 2.0.0\n");

    Ok(())
}
*/

// TODO: Write helper function to generate an index and add tests for
// installing from index.

// The `env install` subcommand is commented out (see `EnvCommand` in cli.rs). Ported to `add`,
// these tests would duplicate existing ones: installing several local-src projects and resolving
// a source through a config file are covered by `add_prunes_unneeded_dependency_by_default` in
// `cli_add_remove.rs`, and the pre-release handling of an unconstrained or version-pinned PURL
// usage (which `add` leaves to the solver, unlike `env install --no-deps`) by the pre-release
// tests in `core/src/solve/pubgrub_tests.rs`. So they are commented out to match instead.
/*

/// Installing multiple projects in sequence via `env install --path` keeps all
/// entries in `env.toml` and physically installs each project into the env
/// directory. All installed projects are non-editable and carry a `src_cksum`.
#[test]
fn env_install_multiple_projects_env_toml() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    // Build two projects with valid .meta.json so checksum_canonical_variant succeeds.
    let (_tmp_a, cwd_a, out) = cli_init_project_basic("a", "env_multi_proj_a", "1.0.0")?;
    out.assert().success();
    std::fs::write(cwd_a.join("A.sysml"), "package A;")?;
    run_sysand_in(&cwd_a, ["include", "A.sysml"], None)?
        .assert()
        .success();

    let (_tmp_b, cwd_b, out) = cli_init_project_basic("a", "env_multi_proj_b", "2.0.0")?;
    out.assert().success();
    std::fs::write(cwd_b.join("B.sysml"), "package B;")?;
    run_sysand_in(&cwd_b, ["include", "B.sysml"], None)?
        .assert()
        .success();

    // Install both projects one after the other.
    run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:env-multi-a",
            "--path",
            cwd_a.as_str(),
        ],
        None,
    )?
    .assert()
    .success()
    .stderr(predicate::str::contains("`urn:kpar:env-multi-a` 1.0.0"));

    run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "urn:kpar:env-multi-b",
            "--path",
            cwd_b.as_str(),
        ],
        None,
    )?
    .assert()
    .success()
    .stderr(predicate::str::contains("`urn:kpar:env-multi-b` 2.0.0"));

    let env_toml = std::fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;

    // Both entries are present and non-editable.
    assert!(
        env_toml.contains("urn:kpar:env-multi-a"),
        "proj_a missing from env.toml"
    );
    assert!(
        env_toml.contains("urn:kpar:env-multi-b"),
        "proj_b missing from env.toml"
    );
    assert!(
        env_toml.contains("src_cksum"),
        "expected src_cksum for installed projects"
    );
    assert!(
        !env_toml.contains("editable = true"),
        "env install must not produce editable entries"
    );

    // Project files are physically present inside the env.
    assert!(
        cwd.join(DEFAULT_ENV_NAME)
            .join("lib/kpar.env-multi-a_1.0.0")
            .is_dir()
    );
    assert!(
        cwd.join(DEFAULT_ENV_NAME)
            .join("lib/kpar.env-multi-b_2.0.0")
            .is_dir()
    );

    // env list reports both.
    run_sysand_in(&cwd, ["env", "list"], None)?
        .assert()
        .success()
        .stdout(predicate::str::contains("`urn:kpar:env-multi-a` 1.0.0"))
        .stdout(predicate::str::contains("`urn:kpar:env-multi-b` 2.0.0"));

    Ok(())
}

/// `env install <IRI>`, resolving the source through a config file override
/// rather than `--path`, must leave the installed project in place: it must
/// still be on disk and registered in `env.toml` once the command returns.
#[test]
fn env_install_via_config_override_survives() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, out) = cli_init_project_basic("t", "env_install_survives_app", "1.0.0")?;
    out.assert().success();

    let (_tmp_dep, cwd_dep, out) =
        cli_init_project_basic("a", "env_install_survives_dep", "1.0.0")?;
    let relative_cwd_dep = relativize_path(&cwd_dep, &cwd).unwrap();
    out.assert().success();

    let config_path = cwd.join("sysand.toml");
    std::fs::write(
        &config_path,
        format!(
            r#"[[project]]
identifiers = ["urn:kpar:env-install-survives-dep"]
sources = [
    {{ src_path = "{relative_cwd_dep}" }},
]
"#
        ),
    )?;

    let out = run_sysand_in(
        &cwd,
        ["env", "install", "urn:kpar:env-install-survives-dep"],
        Some(config_path.as_str()),
    )?;

    out.assert().success().stderr(predicate::str::contains(
        "`urn:kpar:env-install-survives-dep` 1.0.0",
    ));

    assert!(
        cwd.join(DEFAULT_ENV_NAME)
            .join("lib/kpar.env-install-survives-dep_1.0.0")
            .is_dir(),
        "the project must still be on disk once `env install` returns"
    );

    let env_toml = std::fs::read_to_string(cwd.join(DEFAULT_ENV_NAME).join(METADATA_PATH))?;
    assert!(
        env_toml.contains("env-install-survives-dep"),
        "the project must still be registered in env.toml once `env install` returns: {env_toml}"
    );

    Ok(())
}

/// `sysand env install --no-deps <PURL>` with no version given must install
/// the same version the dependency-solving path would: an unconstrained
/// `pkg:sysand` usage defaults to `*`, which excludes pre-releases
#[test]
fn env_install_no_deps_purl_ignores_prereleases() -> Result<(), Box<dyn std::error::Error>> {
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    let mut server = Server::new();

    let (kpar_bytes, info, meta) = build_index_kpar_bytes("widget", "2.0.0");
    let kpar_digest_hex = sha256_lowercase_hex(&kpar_bytes);

    let config_mock = server
        .mock("GET", "/sysand-index-config.json")
        .with_status(404)
        .expect_at_least(1)
        .create();

    // Descending order, as the index protocol requires.
    let versions_mock = server
        .mock("GET", "/acme/widget/versions.json")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(versions_json_body(&[
            versions_json_entry_body(
                "3.0.0-beta.1",
                42,
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            ),
            versions_json_entry_body("2.0.0", kpar_bytes.len(), &kpar_digest_hex),
        ]))
        .expect_at_least(1)
        .create();

    let (_, prerelease_info, prerelease_meta) = build_index_kpar_bytes("widget", "3.0.0-beta.1");
    for (version, version_info, version_meta) in [
        ("3.0.0-beta.1", &prerelease_info, &prerelease_meta),
        ("2.0.0", &info, &meta),
    ] {
        server
            .mock(
                "GET",
                format!("/acme/widget/{version}/.project.json").as_str(),
            )
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(serde_json::to_string(version_info)?)
            .create();
        server
            .mock("GET", format!("/acme/widget/{version}/.meta.json").as_str())
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(serde_json::to_string(version_meta)?)
            .create();
    }

    let kpar_mock = server
        .mock("GET", "/acme/widget/2.0.0/project.kpar")
        .with_status(200)
        .with_header("content-type", "application/zip")
        .with_body(&kpar_bytes)
        .expect_at_least(1)
        .create();

    // The whole point: the prerelease archive is never fetched.
    let prerelease_kpar_mock = server
        .mock("GET", "/acme/widget/3.0.0-beta.1/project.kpar")
        .with_status(200)
        .with_header("content-type", "application/zip")
        .expect(0)
        .create();

    let out = run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "pkg:sysand/acme/widget",
            "--no-deps",
            "--default-index",
            &server.url(),
        ],
        None,
    )?;
    out.assert().success();

    let env_toml = std::fs::read_to_string(
        cwd.join(Utf8Path::new(DEFAULT_ENV_NAME))
            .join(METADATA_PATH),
    )?;
    assert!(
        env_toml.contains(r#"version = "2.0.0""#),
        "expected 2.0.0 to be installed; env.toml:\n{env_toml}"
    );
    assert!(
        !env_toml.contains("3.0.0-beta.1"),
        "prerelease must not be installed; env.toml:\n{env_toml}"
    );

    config_mock.assert();
    versions_mock.assert();
    kpar_mock.assert();
    prerelease_kpar_mock.assert();

    Ok(())
}

/// A PURL project with nothing but prereleases published fails and the
/// error names the versions found
#[test]
fn env_install_no_deps_purl_with_only_prereleases_fails() -> Result<(), Box<dyn std::error::Error>>
{
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    let mut server = Server::new();

    let config_mock = server
        .mock("GET", "/sysand-index-config.json")
        .with_status(404)
        .expect_at_least(1)
        .create();

    let versions_mock = server
        .mock("GET", "/acme/widget/versions.json")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(versions_json_body(&[
            versions_json_entry_body(
                "1.0.0-beta.1",
                42,
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            ),
            versions_json_entry_body(
                "1.0.0-alpha.1",
                42,
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            ),
        ]))
        .expect_at_least(1)
        .create();

    for version in ["1.0.0-beta.1", "1.0.0-alpha.1"] {
        let (_, info, meta) = build_index_kpar_bytes("widget", version);
        server
            .mock(
                "GET",
                format!("/acme/widget/{version}/.project.json").as_str(),
            )
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(serde_json::to_string(&info)?)
            .create();
        server
            .mock("GET", format!("/acme/widget/{version}/.meta.json").as_str())
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(serde_json::to_string(&meta)?)
            .create();
    }

    let out = run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "pkg:sysand/acme/widget",
            "--no-deps",
            "--default-index",
            &server.url(),
        ],
        None,
    )?;

    out.assert().failure().stderr(
        predicate::str::contains("only pre-releases (1.0.0-beta.1, 1.0.0-alpha.1)").and(
            predicate::str::contains("pass the version to use one of them"),
        ),
    );

    config_mock.assert();
    versions_mock.assert();

    Ok(())
}

/// `sysand env install <PURL> <version>` installs exactly the given version
#[test]
fn env_install_no_deps_purl_named_prerelease_is_installed() -> Result<(), Box<dyn std::error::Error>>
{
    let (_temp_dir, cwd, _) = run_sysand(["env"], None)?;

    let mut server = Server::new();

    let (kpar_bytes, info, meta) = build_index_kpar_bytes("widget", "3.0.0-beta.1");
    let kpar_digest_hex = sha256_lowercase_hex(&kpar_bytes);

    let config_mock = server
        .mock("GET", "/sysand-index-config.json")
        .with_status(404)
        .expect_at_least(1)
        .create();

    let versions_mock = server
        .mock("GET", "/acme/widget/versions.json")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(versions_json_body(&[versions_json_entry_body(
            "3.0.0-beta.1",
            kpar_bytes.len(),
            &kpar_digest_hex,
        )]))
        .expect_at_least(1)
        .create();

    let project_json_mock = server
        .mock("GET", "/acme/widget/3.0.0-beta.1/.project.json")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(serde_json::to_string(&info)?)
        .expect_at_least(1)
        .create();

    let meta_json_mock = server
        .mock("GET", "/acme/widget/3.0.0-beta.1/.meta.json")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(serde_json::to_string(&meta)?)
        .expect_at_least(1)
        .create();

    let kpar_mock = server
        .mock("GET", "/acme/widget/3.0.0-beta.1/project.kpar")
        .with_status(200)
        .with_header("content-type", "application/zip")
        .with_body(&kpar_bytes)
        .expect_at_least(1)
        .create();

    let out = run_sysand_in(
        &cwd,
        [
            "env",
            "install",
            "pkg:sysand/acme/widget",
            "3.0.0-beta.1",
            "--no-deps",
            "--default-index",
            &server.url(),
        ],
        None,
    )?;
    out.assert().success();

    let env_toml = std::fs::read_to_string(
        cwd.join(Utf8Path::new(DEFAULT_ENV_NAME))
            .join(METADATA_PATH),
    )?;
    assert!(
        env_toml.contains(r#"version = "3.0.0-beta.1""#),
        "expected the named prerelease to be installed; env.toml:\n{env_toml}"
    );

    config_mock.assert();
    versions_mock.assert();
    project_json_mock.assert();
    meta_json_mock.assert();
    kpar_mock.assert();

    Ok(())
}
*/
