// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: © 2025 Sysand contributors <opensource@sensmetry.com>

use std::{
    cmp::Ordering,
    collections::HashSet,
    fmt::Display,
    hash::{DefaultHasher, Hash, Hasher},
    str::FromStr,
};

use fluent_uri::Iri;
use semver::Version;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use toml_edit::{
    Array, ArrayOfTables, DocumentMut, Formatted, InlineTable, Item, Table, Value, value,
};
use typed_path::Utf8UnixPathBuf;

use crate::{
    env::ReadEnvironment,
    project::{
        ProjectRead,
        utils::{deserialize_unix_path, serialize_unix_path},
    },
};

pub const LOCKFILE_PREFIX: &str = "# This file is automatically generated by Sysand and is not intended to be edited manually.\n\n";
pub const CURRENT_LOCK_VERSION: &str = "0.3";
pub const SUPPORTED_LOCK_VERSIONS: &[&str] = &[CURRENT_LOCK_VERSION];

pub const LOCKFILE_ENTRIES: &[&str] = &["lock_version", "project"];

#[derive(Clone, Debug, Deserialize, PartialEq)]
pub struct Lock {
    pub lock_version: String,
    #[serde(rename = "project", skip_serializing_if = "Vec::is_empty", default)]
    pub projects: Vec<Project>,
}

impl Default for Lock {
    fn default() -> Self {
        Lock {
            lock_version: CURRENT_LOCK_VERSION.to_string(),
            projects: vec![],
        }
    }
}

#[derive(Debug, Error)]
pub enum VersionError {
    #[error("lockfile version `{0}` is not supported")]
    Unsupported(String),
    #[error("lockfile version is missing")]
    Missing,
}

fn check_lock_version(document: &DocumentMut) -> Result<(), VersionError> {
    if let Some(Item::Value(Value::String(lock_version))) = document.get("lock_version") {
        let version = lock_version.value();
        if SUPPORTED_LOCK_VERSIONS.contains(&version.as_str()) {
            Ok(())
        } else {
            Err(VersionError::Unsupported(version.clone()))
        }
    } else {
        Err(VersionError::Missing)
    }
}

#[derive(Debug, Error)]
pub enum ParseError {
    #[error("failed to parse lockfile: {0}")]
    Toml(#[from] toml::de::Error),
    #[error("failed to parse lockfile: {0}")]
    TomlEdit(#[from] toml_edit::TomlError),
    #[error(transparent)]
    Validation(#[from] ValidationError),
    #[error(transparent)]
    Version(#[from] VersionError),
}

impl FromStr for Lock {
    type Err = ParseError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let document = DocumentMut::from_str(s)?;
        check_lock_version(&document)?;

        for (field, _) in document.iter() {
            if !LOCKFILE_ENTRIES.contains(&field) {
                log::warn!("unknown field `{field}` in lockfile");
            }
        }
        for (field, value, name) in document
            .get("project")
            .and_then(Item::as_array_of_tables)
            .into_iter()
            .flat_map(|projects| projects.iter())
            .flat_map(|project| {
                project
                    .into_iter()
                    .map(|(field, value)| (field, value, project.get("name")))
            })
        {
            if !PROJECT_ENTRIES.contains(&field) {
                log::warn!(
                    "unknown field `{}` in {} in lockfile",
                    field,
                    project_with(name)
                );
            } else if field == "sources" {
                for (field, _) in value
                    .as_array()
                    .into_iter()
                    .flat_map(|sources| sources.iter())
                    .map(|source| source.as_inline_table())
                    .flat_map(|s| s.into_iter())
                    .flat_map(|s| s.into_iter())
                {
                    if !SOURCE_ENTRIES.contains(&field) {
                        log::warn!(
                            "unknown field `{}` in source for {} in lockfile",
                            field,
                            project_with(name)
                        );
                    }
                }
            }
        }

        // TODO: find a way to not reparse
        let lock: Lock = toml::from_str(s)?;
        lock.validate()?;
        Ok(lock)
    }
}

fn project_with<D: Display>(name: Option<D>) -> String {
    if let Some(name) = name {
        format!("project with name `{}`", name)
    } else {
        "project without name".to_string()
    }
}

impl Display for Lock {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.to_toml())
    }
}

#[derive(Debug, Error)]
pub enum ResolutionError<EnvironmentError> {
    #[error(transparent)]
    CandidateProjects(EnvironmentError),
    #[error("missing projects: {0:?}")]
    MissingProjects(Vec<Project>),
}

#[derive(Debug, Error)]
pub enum ValidationError {
    #[error("lockfile version `{0}` is not supported")]
    UnsupportedVersion(String),
    #[error("symbol name `{0}` is exported by more than one project in lockfile")]
    NameCollision(String),
    #[error("project identifier `{0}` is\nspecified by more than one project in lockfile")]
    ProjectIdCollision(String),
    #[error("{0} does not have an identifier")]
    ProjectWithoutId(String),
    #[error("unsatisfied usage `{usage}` for {project_with_name} in lockfile")]
    UnsatisfiedUsage {
        usage: String,
        project_with_name: String,
    },
    // #[error(
    //     "unsatisfied usage `{usage}` for {project_with_name} (found version `{version}`) in lockfile"
    // )]
    // UnsatisfiedUsageVersion {
    //     usage: String,
    //     version: String,
    //     project_with_name: String,
    // },
    #[error("invalid format of SHA256 checksum `{checksum}` for {project_with_name} in lockfile")]
    InvalidChecksumFormat {
        checksum: String,
        project_with_name: String,
    },
}

pub type ProjectResolution<Env> = (
    Project,
    Option<<Env as ReadEnvironment>::InterchangeProjectRead>,
);

impl Lock {
    pub fn resolve_projects<Env: ReadEnvironment>(
        &self,
        env: &Env,
    ) -> Result<Vec<ProjectResolution<Env>>, ResolutionError<Env::ReadError>> {
        let mut missing = vec![];
        let mut found = vec![];

        for project in &self.projects {
            // Projects without sources (default for standard libraries) and
            // projects with editable sources won't be installed in environment.
            match project.sources.as_slice() {
                [] => {
                    continue;
                }
                [Source::Editable { editable: _ }, ..] => {
                    found.push((project.clone(), None));
                    continue;
                }
                _ => {}
            }

            let checksum = &project.checksum;

            let mut resolved_project = None;

            'outer: for iri in &project.identifiers {
                for candidate_project in env
                    .candidate_projects(iri)
                    .map_err(ResolutionError::CandidateProjects)?
                {
                    if let Ok(Some(candidate_checksum)) = candidate_project.checksum_canonical_hex()
                        && candidate_checksum == *checksum
                    {
                        resolved_project = Some(candidate_project);
                        break 'outer;
                    }
                }
            }

            if resolved_project.is_some() {
                found.push((project.clone(), resolved_project));
            } else {
                missing.push(project.clone());
            }
        }

        if !missing.is_empty() {
            return Err(ResolutionError::MissingProjects(missing));
        }

        Ok(found)
    }

    pub fn to_toml(&self) -> DocumentMut {
        let mut doc = DocumentMut::new();
        doc.decor_mut().set_prefix(LOCKFILE_PREFIX);
        doc.insert("lock_version", value(Value::from(&self.lock_version)));

        let mut projects = ArrayOfTables::new();
        for project in &self.projects {
            projects.push(project.to_toml());
        }
        doc.insert("project", Item::ArrayOfTables(projects));

        doc
    }

    pub fn validate(&self) -> Result<(), ValidationError> {
        self.validate_lock_version()?;
        self.check_name_collision()?;
        self.validate_usages()?;
        self.validate_checksum_format()?;
        Ok(())
    }

    fn validate_lock_version(&self) -> Result<(), ValidationError> {
        if SUPPORTED_LOCK_VERSIONS.contains(&self.lock_version.as_str()) {
            Ok(())
        } else {
            Err(ValidationError::UnsupportedVersion(
                self.lock_version.clone(),
            ))
        }
    }

    fn check_name_collision(&self) -> Result<(), ValidationError> {
        let mut seen_projects = HashSet::new();
        let mut seen_exports = HashSet::new();
        for project in &self.projects {
            if !seen_projects.insert(project) {
                let id = match project.identifiers.first() {
                    Some(id) => id,
                    None => {
                        return Err(ValidationError::ProjectWithoutId(project_with(
                            project.name.as_ref(),
                        )));
                    }
                };
                return Err(ValidationError::ProjectIdCollision(id.to_string()));
            }
            for name in &project.exports {
                if !seen_exports.insert(name) {
                    return Err(ValidationError::NameCollision(name.clone()));
                }
            }
        }
        Ok(())
    }

    fn validate_usages(&self) -> Result<(), ValidationError> {
        let mut iri_versions = HashSet::new();
        for project in &self.projects {
            let _ = Version::parse(&project.version).inspect_err(|err| {
                log::warn!(
                    "invalid semantic version `{}` for project {}\n\
                        {:>8} {}",
                    project.version,
                    project_with(project.name.as_ref()),
                    ' ',
                    err
                );
            });
            for iri in &project.identifiers {
                iri_versions.insert(iri.clone());
            }
        }
        for project in &self.projects {
            for usage in &project.usages {
                if !iri_versions.contains(&usage.resource) {
                    return Err(ValidationError::UnsatisfiedUsage {
                        usage: usage.resource.clone(),
                        project_with_name: project_with(project.name.clone()),
                    });
                }
            }
        }
        Ok(())
    }

    fn validate_checksum_format(&self) -> Result<(), ValidationError> {
        let fail = self
            .projects
            .iter()
            .map(|p| (p.checksum.clone(), p.name.clone()))
            .find(|(cs, _)| cs.len() != 64 || !cs.bytes().all(|c| c.is_ascii_hexdigit()));
        if let Some((checksum, name)) = fail {
            Err(ValidationError::InvalidChecksumFormat {
                checksum,
                project_with_name: project_with(name),
            })
        } else {
            Ok(())
        }
    }

    /// Should always be called before writing lock to file.
    /// Makes lock canonical:
    ///
    /// - sorts all the collections
    /// - canonicalizes project checksums
    ///
    /// Does not change contents or semantics.
    pub fn canonicalize(mut self) -> Self {
        self.sort();
        self.canonicalize_checksums();
        // Check that we aren't generating invalid lockfiles
        debug_assert!(self.validate().map(|_| true).unwrap());
        self
    }

    pub fn sort(&mut self) {
        for project in &mut self.projects {
            project.exports.sort();
            project.identifiers.sort();
            project.usages.sort();
            project.sources.sort();
        }
        self.projects.sort();
    }

    pub fn canonicalize_checksums(&mut self) {
        for project in &mut self.projects {
            project.checksum.make_ascii_lowercase();
        }
    }
}

pub const PROJECT_ENTRIES: &[&str] = &[
    "name",
    "publisher",
    "version",
    "exports",
    "identifiers",
    "usages",
    "sources",
    "checksum",
];

/// Fields that are not critical for using the lockfile use `Option`
#[derive(Clone, Eq, Debug, Deserialize, PartialEq)]
pub struct Project {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub publisher: Option<String>,
    pub version: String,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub exports: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub identifiers: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub usages: Vec<Usage>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub sources: Vec<Source>,
    pub checksum: String,
}

impl std::hash::Hash for Project {
    /// Project hash is its canonical checksum.
    /// IRIs could also be used for this, but they may differ in amount
    /// (including having no known IRIs) and/or ordering between different
    /// project instances
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.checksum.hash(state);
    }
}

impl Ord for Project {
    fn cmp(&self, other: &Self) -> Ordering {
        self.name
            .cmp(&other.name)
            .then(self.exports.cmp(&other.exports))
            // Since valid lockfiles should never have overlap in exports
            // further sorting is only for debugging purposes.
            .then(self.identifiers.cmp(&other.identifiers))
            .then(self.version.cmp(&other.version))
    }
}

impl PartialOrd for Project {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub struct ProjectHash(u64);
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub struct StrHash(u64);

pub fn hash_str(val: &str) -> StrHash {
    let mut hasher = DefaultHasher::new();
    val.hash(&mut hasher);
    StrHash(hasher.finish())
}

impl Project {
    pub fn to_toml(&self) -> Table {
        let mut table = Table::new();
        if let Some(name) = &self.name {
            table.insert("name", value(name));
        }
        table.insert("version", value(&self.version));
        let exports = multiline_array(self.exports.iter().map(Value::from));
        if !exports.is_empty() {
            table.insert("exports", value(exports));
        }
        let identifiers = multiline_array(self.identifiers.iter().map(Value::from));
        if !identifiers.is_empty() {
            table.insert("identifiers", value(identifiers));
        }
        let usages = multiline_array(self.usages.iter().map(|u| u.to_toml()));
        if !usages.is_empty() {
            table.insert("usages", value(usages));
        }
        let sources = multiline_array(self.sources.iter().map(|s| s.to_toml()));
        if !sources.is_empty() {
            table.insert("sources", value(sources));
        }
        table.insert("checksum", value(&self.checksum));
        table
    }

    /// Project hash is its canonical checksum
    pub fn hash_val(&self) -> ProjectHash {
        let mut hasher = DefaultHasher::new();
        self.hash(&mut hasher);
        ProjectHash(hasher.finish())
    }
}

const SOURCE_ENTRIES: &[&str] = &[
    "editable",
    "src_path",
    "kpar_path",
    "registry",
    "remote_src",
    "remote_kpar",
    "remote_kpar_size",
    "remote_git",
    "remote_api",
];

#[derive(Clone, Eq, Debug, Deserialize, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(untagged)]
pub enum Source {
    // Path must be a Unix path relative to workspace root
    Editable {
        #[serde(
            deserialize_with = "deserialize_unix_path",
            serialize_with = "serialize_unix_path"
        )]
        editable: Utf8UnixPathBuf,
    },
    LocalSrc {
        #[serde(
            deserialize_with = "deserialize_unix_path",
            serialize_with = "serialize_unix_path"
        )]
        src_path: Utf8UnixPathBuf,
    },
    LocalKpar {
        #[serde(
            deserialize_with = "deserialize_unix_path",
            serialize_with = "serialize_unix_path"
        )]
        kpar_path: Utf8UnixPathBuf,
    },
    Registry {
        registry: String,
    },
    RemoteKpar {
        remote_kpar: String,
        remote_kpar_size: Option<u64>,
    },
    RemoteSrc {
        remote_src: String,
    },
    RemoteGit {
        remote_git: String,
    },
    RemoteApi {
        remote_api: String,
    },
}

impl Source {
    pub fn to_toml(&self) -> InlineTable {
        let mut table = InlineTable::new();
        match self {
            Source::Editable { editable } => {
                debug_assert!(
                    editable.is_relative(),
                    "editable project path is absolute: `{editable}`"
                );
                table.insert("editable", Value::from(editable.as_str()));
            }
            Source::LocalKpar { kpar_path } => {
                table.insert("kpar_path", Value::from(kpar_path.as_str()));
            }
            Source::LocalSrc { src_path } => {
                table.insert("src_path", Value::from(src_path.as_str()));
            }
            Source::Registry { registry } => {
                table.insert("registry", Value::from(registry));
            }
            Source::RemoteApi { remote_api } => {
                table.insert("remote_api", Value::from(remote_api));
            }
            Source::RemoteGit { remote_git } => {
                table.insert("remote_git", Value::from(remote_git));
            }
            Source::RemoteKpar {
                remote_kpar,
                remote_kpar_size,
            } => {
                table.insert("remote_kpar", Value::from(remote_kpar));
                if let Some(remote_kpar_size) = remote_kpar_size {
                    let size = i64::try_from(*remote_kpar_size).unwrap();
                    table.insert("remote_kpar_size", Value::Integer(Formatted::new(size)));
                }
            }
            Source::RemoteSrc { remote_src } => {
                table.insert("remote_src", Value::from(remote_src));
            }
        }
        table
    }
}

#[derive(Clone, Eq, Debug, Ord, PartialEq, PartialOrd)]
pub struct Usage {
    pub resource: String,
}

impl From<String> for Usage {
    fn from(resource: String) -> Self {
        Self { resource }
    }
}

impl From<Iri<String>> for Usage {
    fn from(resource: Iri<String>) -> Self {
        Self {
            resource: resource.into_string(),
        }
    }
}

impl Usage {
    pub fn to_toml(&self) -> Value {
        Value::from(&self.resource)
    }
}

impl<'de> Deserialize<'de> for Usage {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        Ok(Usage { resource: s })
    }
}

// impl From<InterchangeProjectUsageRaw> for Usage {
//     fn from(value: InterchangeProjectUsageRaw) -> Usage {
//         Usage {
//             resource: value.resource,
//         }
//     }
// }

// impl From<InterchangeProjectUsage> for Usage {
//     fn from(value: InterchangeProjectUsage) -> Usage {
//         Usage {
//             resource: value.resource.to_string(),
//         }
//     }
// }

pub fn multiline_array(elements: impl Iterator<Item = impl Into<Value>>) -> Array {
    let mut array: Array = elements
        .map(|item| {
            let mut value = item.into();
            value.decor_mut().set_prefix("\n    ");
            value
        })
        .collect();
    array.set_trailing_comma(true);
    array.set_trailing("\n");
    array
}

#[cfg(test)]
#[path = "./lock_tests.rs"]
mod tests;
