// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: © 2025 Sysand contributors <opensource@sensmetry.com>

use std::{fmt::Display, str::FromStr};

use camino::{Utf8Path, Utf8PathBuf};
use serde::Deserialize;
use thiserror::Error;
use toml_edit::{ArrayOfTables, DocumentMut, Item, Table, Value, value};
use typed_path::Utf8UnixPathBuf;

use crate::{
    env::local_directory::LocalReadError,
    lock::{ResolutionError, multiline_array},
    project::{
        local_src::{LocalSrcError, LocalSrcProject},
        utils::{FsIoError, ToUnixPathBuf, deserialize_unix_path, wrapfs},
    },
};

pub const METADATA_PREFIX: &str = "# This file is automatically generated by Sysand and is not intended to be edited manually.\n\n";
pub const CURRENT_METADATA_VERSION: &str = "0.1";
pub const SUPPORTED_METADATA_VERSIONS: &[&str] = &[CURRENT_METADATA_VERSION];

#[derive(Debug, Error)]
pub enum LockToEnvMetadataError {
    #[error(transparent)]
    ResolutionError(#[from] ResolutionError<LocalReadError>),
    #[error(transparent)]
    Canonicalization(#[from] Box<FsIoError>),
}

#[derive(Debug, Deserialize, Clone)]
pub struct EnvMetadata {
    pub version: String,
    #[serde(rename = "project", default)]
    pub projects: Vec<EnvProject>,
}

impl Default for EnvMetadata {
    fn default() -> Self {
        EnvMetadata {
            version: CURRENT_METADATA_VERSION.to_string(),
            projects: vec![],
        }
    }
}

#[derive(Debug, Error)]
#[error("env metadata version `{0}` is not supported")]
pub struct UnsupportedVersionError(String);

#[derive(Debug, Error)]
pub enum ParseError {
    #[error("failed to parse env metadata file: {0}")]
    Toml(#[from] toml::de::Error),
    #[error(transparent)]
    Unsupported(#[from] UnsupportedVersionError),
}

impl Display for EnvMetadata {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.to_toml())
    }
}

impl FromStr for EnvMetadata {
    type Err = ParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let metadata: EnvMetadata = toml::from_str(s)?;

        if !SUPPORTED_METADATA_VERSIONS.contains(&metadata.version.as_str()) {
            return Err(ParseError::Unsupported(UnsupportedVersionError(
                metadata.version.clone(),
            )));
        }

        Ok(metadata)
    }
}

#[derive(Debug, Error)]
pub enum AddProjectError {
    #[error(transparent)]
    ProjectRead(#[from] LocalSrcError),
    #[error("missing project info at `{0}`")]
    MissingInfo(Utf8PathBuf),
}

impl EnvMetadata {
    pub fn to_toml(&self) -> DocumentMut {
        let mut doc = DocumentMut::new();
        doc.decor_mut().set_prefix(METADATA_PREFIX);
        doc.insert("version", value(Value::from(&self.version)));

        let mut projects = ArrayOfTables::new();
        for project in &self.projects {
            projects.push(project.to_toml());
        }
        doc.insert("project", Item::ArrayOfTables(projects));

        doc
    }

    /// Prefer [`find_project_version`] or [`find_project_version_mut`] where
    /// possible.
    pub fn find_project_version_idx<S: AsRef<str>, V: AsRef<str>>(
        &self,
        identifiers: &[S],
        version: V,
    ) -> Option<usize> {
        let version = version.as_ref();
        for (index, project) in self.projects.iter().enumerate() {
            if project.version == version
                && project
                    .identifiers
                    .iter()
                    .any(|iri| identifiers.iter().any(|i| i.as_ref() == iri))
            {
                return Some(index);
            }
        }
        None
    }

    pub fn find_project_version<S: AsRef<str>, V: AsRef<str>>(
        &self,
        identifiers: &[S],
        version: V,
    ) -> Option<&EnvProject> {
        let version = version.as_ref();
        self.projects.iter().find(|p| {
            p.version == version
                && p.identifiers
                    .iter()
                    .any(|iri| identifiers.iter().any(|i| i.as_ref() == iri))
        })
    }
    pub fn find_project_version_mut<S: AsRef<str>, V: AsRef<str>>(
        &mut self,
        identifiers: &[S],
        version: V,
    ) -> Option<&mut EnvProject> {
        let version = version.as_ref();
        self.projects.iter_mut().find(|p| {
            p.version == version
                && p.identifiers
                    .iter()
                    .any(|iri| identifiers.iter().any(|i| i.as_ref() == iri))
        })
    }

    pub fn find_project(&self, identifiers: &[&str]) -> impl Iterator<Item = &EnvProject> {
        self.projects.iter().filter(|p| {
            p.identifiers
                .iter()
                .any(|iri| identifiers.contains(&iri.as_str()))
        })
    }

    pub fn add_project(&mut self, project: EnvProject) {
        if let Some(found) = self.find_project_version_mut(&project.identifiers, &project.version) {
            found.merge_identifiers(&project);
        } else {
            self.projects.push(project);
        }
    }

    pub fn remove_project<S: AsRef<str>, V: AsRef<str>>(&mut self, iri: S, version: Option<V>) {
        if let Some(v) = version {
            self.projects.retain(|p| {
                p.version != v.as_ref() || !p.identifiers.iter().any(|i| i == iri.as_ref())
            });
        } else {
            self.projects
                .retain(|p| !p.identifiers.iter().any(|i| i == iri.as_ref()));
        }
    }

    /// Add `LocalSrcProject` to env. Must have `nominal_path` set.
    pub fn add_local_project(
        &mut self,
        identifiers: Vec<String>,
        project: &LocalSrcProject,
        editable: bool,
        workspace: bool,
    ) -> Result<(), AddProjectError> {
        let info = project
            .get_info()?
            .ok_or(AddProjectError::MissingInfo(project.project_path.clone()))?;
        let project = EnvProject {
            publisher: info.publisher,
            name: Some(info.name),
            version: info.version,
            path: project
                .nominal_path
                .as_ref()
                .expect("BUG: no nominal path for project")
                .to_unix_path_buf(),
            identifiers,
            usages: info.usage.into_iter().map(|u| u.resource).collect(),
            editable,
            workspace,
        };
        self.add_project(project);

        Ok(())
    }

    pub fn project_dir_exists(&self, dir_name: &str) -> bool {
        self.projects
            .iter()
            .any(|p| p.path.file_name().unwrap() == dir_name)
    }
}

/// Metadata describing a project belonging to an environment.
#[derive(Debug, Deserialize, Clone)]
pub struct EnvProject {
    /// Publisher of the project. Intended for display purposes.
    pub publisher: Option<String>,
    /// Name of the project. Intended for display purposes.
    pub name: Option<String>,
    /// Version of the project.
    pub version: String,
    /// Path to the root directory of the project.
    /// If the project is not `editable` this should be relative
    /// to the env directory and otherwise it should be relative
    /// to the workspace root.
    #[serde(deserialize_with = "deserialize_unix_path")]
    pub path: Utf8UnixPathBuf,
    /// List of identifiers (IRIs) used for the project.
    /// The first identifier is considered the canonical
    /// identifier, and if the project is not `editable` this
    /// is the IRI it is installed as. The rest are considered
    /// as aliases. Can only be empty for `editable` projects.
    #[serde(default)]
    pub identifiers: Vec<String>,
    /// Usages of the project. Intended for tools needing to
    /// track the interdependence of project in the environment.
    #[serde(default)]
    pub usages: Vec<String>,
    /// Indicator of wether the project is fully installed in
    /// the environment or located elsewhere.
    #[serde(default)]
    pub editable: bool,
    /// Indicator of wether the project is part of a workspace.
    #[serde(default)]
    pub workspace: bool,
}

impl EnvProject {
    pub fn to_toml(&self) -> Table {
        let mut table = Table::new();
        if let Some(publisher) = &self.publisher {
            table.insert("publisher", value(publisher));
        }
        if let Some(name) = &self.name {
            table.insert("name", value(name));
        }
        table.insert("version", value(&self.version));
        table.insert("path", value(self.path.as_str()));
        if !self.identifiers.is_empty() {
            table.insert(
                "identifiers",
                value(multiline_array(self.identifiers.iter())),
            );
        }
        if !self.usages.is_empty() {
            table.insert("usages", value(multiline_array(self.usages.iter())));
        }
        if self.editable {
            table.insert("editable", value(true));
        }
        if self.workspace {
            table.insert("workspace", value(true));
        }

        table
    }

    /// Adds identifiers from other project.
    /// Should only be done if the underlying projects are the same.
    /// In particular they must have the same version.
    pub fn merge_identifiers(&mut self, other: &EnvProject) {
        assert_eq!(
            self.version, other.version,
            "attempting to merge identifiers for projects with different versions"
        );

        for iri in &other.identifiers {
            if !self.identifiers.contains(iri) {
                self.identifiers.push(iri.clone());
            }
        }
    }
}

#[derive(Error, Debug)]
pub enum EnvMetadataError {
    #[error("failed to deserialize TOML file `{0}`: {1}")]
    Toml(Box<Utf8Path>, toml::de::Error),
    #[error(transparent)]
    Io(#[from] Box<FsIoError>),
    #[error(transparent)]
    Unsupported(UnsupportedVersionError),
}

pub fn load_env_metadata<P: AsRef<Utf8Path>>(path: P) -> Result<EnvMetadata, EnvMetadataError> {
    let metadata = wrapfs::read_to_string(path.as_ref())?;
    parse_env_metadata(path, metadata)
}

pub fn parse_env_metadata<P: AsRef<Utf8Path>>(
    path: P,
    metadata: String,
) -> Result<EnvMetadata, EnvMetadataError> {
    let result = EnvMetadata::from_str(metadata.as_str());

    result.map_err(|parse_err| match parse_err {
        ParseError::Toml(err) => EnvMetadataError::Toml(path.as_ref().to_owned().into(), err),
        ParseError::Unsupported(err) => EnvMetadataError::Unsupported(err),
    })
}
