// SPDX-FileCopyrightText: © 2025 Sysand contributors <opensource@sensmetry.com>
// SPDX-License-Identifier: MIT OR Apache-2.0

use std::{fmt::Display, num::TryFromIntError, str::FromStr};

use camino::{Utf8Path, Utf8PathBuf};
use serde::Deserialize;
use thiserror::Error;
use toml_edit::{Array, ArrayOfTables, DocumentMut, Item, Table, Value, value};

use crate::{
    commands::sources::{LocalSourcesError, do_sources_local_src_project_no_deps},
    env::local_directory::{LocalDirectoryEnvironment, LocalReadError},
    lock::{Lock, ResolutionError, Source, multiline_array},
    project::{
        local_src::{LocalSrcError, LocalSrcProject},
        utils::{FsIoError, relativize_path, wrapfs},
    },
};

pub const METADATA_PREFIX: &str = "# This file is automatically generated by Sysand and is not intended to be edited manually.\n\n";
pub const CURRENT_METADATA_VERSION: &str = "0.1";
pub const SUPPORTED_METADATA_VERSIONS: &[&str] = &[CURRENT_METADATA_VERSION];

#[derive(Debug, Error)]
pub enum LockToEnvMetadataError {
    #[error(transparent)]
    ResolutionError(#[from] ResolutionError<LocalReadError>),
    #[error("too many dependencies, unable to convert to i64: {0}")]
    TooManyDependencies(TryFromIntError),
    #[error(transparent)]
    LocalSources(#[from] LocalSourcesError),
    #[error(transparent)]
    Canonicalization(#[from] Box<FsIoError>),
}

impl Lock {
    pub fn to_env_metadata<P: AsRef<Utf8Path>>(
        &self,
        env: &LocalDirectoryEnvironment,
        root_path: P,
    ) -> Result<EnvMetadata, LockToEnvMetadataError> {
        let resolved_projects = self.resolve_projects(env)?;

        let mut metadata = EnvMetadata::default();
        for (project, storage) in resolved_projects {
            let usages = project
                .usages
                .iter()
                .map(|usage| usage.resource.clone())
                .collect();

            if let Some(storage) = storage {
                let path = storage
                    .root_path()
                    .strip_prefix(env.root_path())
                    .expect("path to project in env does not share a prefix with path to env")
                    .to_owned();
                metadata.projects.push(EnvProject {
                    publisher: project.publisher,
                    name: project.name,
                    version: project.version,
                    path,
                    identifiers: project.identifiers,
                    usages,
                    editable: false,
                    files: None,
                });
            } else if let [Source::Editable { editable }, ..] = project.sources.as_slice() {
                let editable_project = LocalSrcProject {
                    nominal_path: None,
                    project_path: wrapfs::canonicalize(root_path.as_ref().join(editable.as_str()))?,
                };
                let files = do_sources_local_src_project_no_deps(&editable_project, true)?
                    .into_iter()
                    .map(|path| {
                        relativize_path(path, root_path.as_ref())
                            .expect("cannot relativize path to file in editable project")
                    })
                    .collect();
                metadata.projects.push(EnvProject {
                    publisher: project.publisher,
                    name: project.name,
                    version: project.version,
                    path: editable.as_str().into(),
                    identifiers: project.identifiers,
                    usages,
                    editable: true,
                    files: Some(files),
                });
            }
        }

        Ok(metadata)
    }
}

#[derive(Debug, Deserialize)]
pub struct EnvMetadata {
    pub version: String,
    #[serde(rename = "project", skip_serializing_if = "Vec::is_empty", default)]
    pub projects: Vec<EnvProject>,
}

impl Default for EnvMetadata {
    fn default() -> Self {
        EnvMetadata {
            version: CURRENT_METADATA_VERSION.to_string(),
            projects: vec![],
        }
    }
}

#[derive(Debug, Error)]
#[error("env metadata version `{0}` is not supported")]
pub struct UnsupportedVersionError(String);

#[derive(Debug, Error)]
pub enum ParseError {
    #[error("failed to parse env metadata file: {0}")]
    Toml(#[from] toml::de::Error),
    #[error(transparent)]
    Unsupported(#[from] UnsupportedVersionError),
}

impl Display for EnvMetadata {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.to_toml())
    }
}

impl FromStr for EnvMetadata {
    type Err = ParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let metadata: EnvMetadata = toml::from_str(s)?;

        if !SUPPORTED_METADATA_VERSIONS.contains(&metadata.version.as_str()) {
            return Err(ParseError::Unsupported(UnsupportedVersionError(
                metadata.version.clone(),
            )));
        }

        Ok(metadata)
    }
}

#[derive(Debug, Error)]
pub enum AddProjectError {
    #[error(transparent)]
    ProjectRead(#[from] LocalSrcError),
    #[error("missing project info at `{0}`")]
    MissingInfo(Utf8PathBuf),
}

impl EnvMetadata {
    pub fn to_toml(&self) -> DocumentMut {
        let mut doc = DocumentMut::new();
        doc.decor_mut().set_prefix(METADATA_PREFIX);
        doc.insert("version", value(Value::from(&self.version)));

        let mut projects = ArrayOfTables::new();
        for project in &self.projects {
            projects.push(project.to_toml());
        }
        doc.insert("project", Item::ArrayOfTables(projects));

        doc
    }

    fn find_project(&self, identifiers: &[String], version: &String) -> Option<usize> {
        for (index, project) in self.projects.iter().enumerate() {
            if &project.version == version
                && project
                    .identifiers
                    .iter()
                    .any(|iri| identifiers.contains(iri))
            {
                return Some(index);
            }
        }
        None
    }

    pub fn add_project(&mut self, project: EnvProject) {
        if let Some(found) = self.find_project(&project.identifiers, &project.version) {
            self.projects[found].merge(&project);
        } else {
            self.projects.push(project);
        }
    }

    pub fn remove_project<S: AsRef<str>, V: AsRef<str>>(&mut self, iri: S, version: Option<V>) {
        if let Some(v) = version {
            self.projects.retain(|p| {
                p.version != v.as_ref() || !p.identifiers.iter().any(|i| i == iri.as_ref())
            });
        } else {
            self.projects
                .retain(|p| !p.identifiers.iter().any(|i| i == iri.as_ref()));
        }
    }

    /// Add `LocalSrcProject` to env. Must have `nominal_path` set.
    pub fn add_local_project(
        &mut self,
        identifiers: Vec<String>,
        project: LocalSrcProject,
        editable: bool,
    ) -> Result<(), AddProjectError> {
        let info = project
            .get_info()?
            .ok_or(AddProjectError::MissingInfo(project.project_path.clone()))?;
        let project = EnvProject {
            publisher: info.publisher,
            name: Some(info.name),
            version: info.version,
            path: project
                .nominal_path
                .expect("expected nominal path for project"),
            identifiers,
            usages: info.usage.into_iter().map(|u| u.resource).collect(),
            editable,
            files: None,
        };
        self.add_project(project);

        Ok(())
    }

    pub fn merge(&mut self, other: EnvMetadata) {
        for project in other.projects {
            self.add_project(project)
        }
    }
}

/// Metadata describing a project belonging to an environment.
#[derive(Debug, Deserialize)]
pub struct EnvProject {
    /// Publisher of the project. Intended for display purposes.
    pub publisher: Option<String>,
    /// Name of the project. Intended for display purposes.
    pub name: Option<String>,
    /// Version of the project.
    pub version: String,
    /// Path to the root directory of the project.
    /// If the project is not `editable` this should be relative
    /// to the env directory and otherwise it should be relative
    /// to the workspace root.
    pub path: Utf8PathBuf,
    /// List of identifiers (IRIs) used for the project.
    /// The first identifier is to. be considered the canonical
    /// identifier, and if the project is not `editable` this
    /// is the IRI it is installed as. The rest are considered
    /// as aliases. Can only be empty for `editable` projects.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub identifiers: Vec<String>,
    /// Usages of the project. Intended for tools needing to
    /// track the interdependence of project in the environment.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub usages: Vec<String>,
    /// Indicator of wether the project is fully installed in
    /// the environment or located elsewhere.
    #[serde(skip_serializing_if = "bool::is_false", default)]
    pub editable: bool,
    /// In case of an `editable` project these are the files
    /// belonging to the project. Intended for tools that
    /// are not able to natively parse and understand the
    /// projects `.meta.json` file. Paths should be relative
    /// to the `path` of the project.
    pub files: Option<Vec<Utf8PathBuf>>,
}

impl EnvProject {
    pub fn to_toml(&self) -> Table {
        let mut table = Table::new();
        if let Some(publisher) = &self.publisher {
            table.insert("publisher", value(publisher));
        }
        if let Some(name) = &self.name {
            table.insert("name", value(name));
        }
        table.insert("version", value(&self.version));
        table.insert("path", value(self.path.as_str()));
        if !self.identifiers.is_empty() {
            table.insert(
                "identifiers",
                value(multiline_array(self.identifiers.iter())),
            );
        }
        if !self.usages.is_empty() {
            table.insert("usages", value(multiline_array(self.usages.iter())));
        }
        if self.editable {
            table.insert("editable", value(true));
        }
        if let Some(files) = &self.files {
            let file_iter = files.iter().map(|f| Value::from(f.as_str()));
            if files.is_empty() {
                table.insert("files", value(Array::from_iter(file_iter)));
            } else {
                table.insert("files", value(multiline_array(file_iter)));
            }
        }

        table
    }

    pub fn merge(&mut self, other: &EnvProject) {
        for iri in &other.identifiers {
            if !self.identifiers.contains(iri) {
                self.identifiers.push(iri.clone());
            }
        }
    }
}

#[derive(Error, Debug)]
pub enum EnvMetadataReadError {
    #[error("failed to deserialize TOML file `{0}`: {1}")]
    Toml(Box<Utf8Path>, toml::de::Error),
    #[error(transparent)]
    Io(#[from] Box<FsIoError>),
    #[error(transparent)]
    Unsupported(UnsupportedVersionError),
}

impl From<FsIoError> for EnvMetadataReadError {
    fn from(err: FsIoError) -> Self {
        Self::Io(Box::new(err))
    }
}

pub fn load_env_metadata<P: AsRef<Utf8Path>>(path: P) -> Result<EnvMetadata, EnvMetadataReadError> {
    let result = EnvMetadata::from_str(wrapfs::read_to_string(path.as_ref())?.as_str());

    result.map_err(|parse_err| match parse_err {
        ParseError::Toml(err) => EnvMetadataReadError::Toml(path.as_ref().to_owned().into(), err),
        ParseError::Unsupported(err) => EnvMetadataReadError::Unsupported(err),
    })
}
