// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: © 2025 Sysand contributors <opensource@sensmetry.com>

#[cfg(feature = "filesystem")]
mod filesystem_tests {
    use std::{
        error::Error,
        io::{Cursor, Read},
        path::Path,
    };

    use camino::Utf8Path;
    use camino_tempfile::tempdir;
    use indexmap::IndexMap;
    use sysand_core::{
        commands::env::do_env_local_dir,
        env::{
            DEFAULT_ENV_NAME, ReadEnvironment, WriteEnvironment,
            local_directory::LocalDirectoryEnvironment, utils::clone_project,
        },
        info::do_info,
        model::{InterchangeProjectInfoRaw, InterchangeProjectMetadataRaw, format_created_now},
        project::{ProjectMut, ProjectRead, memory::InMemoryProject},
        resolve::env::EnvResolver,
    };
    use typed_path::Utf8UnixPath;

    const DEFAULT_ENV_FILE_CONTENTS: &str =
    "# This file is automatically generated by Sysand and is not intended to be edited manually.

version = \"0.1\"
";

    fn ls_dir<P: AsRef<Path>>(path: P) -> Vec<String> {
        let path = path.as_ref().to_path_buf().clone();

        let mut files: Vec<String> = std::fs::read_dir(&path)
            .unwrap()
            .map(|entry| {
                let inner_path = entry.unwrap().path();

                assert!(inner_path.is_dir() || inner_path.is_file());

                inner_path
                    .strip_prefix(&path)
                    .unwrap()
                    .as_os_str()
                    .to_string_lossy()
                    .to_string()
            })
            .collect();

        files.sort();

        files
    }

    #[test]
    fn env_basic() -> Result<(), Box<dyn Error>> {
        let cwd = tempdir()?;
        let env_path = Utf8Path::new(DEFAULT_ENV_NAME);
        let directory_environment = do_env_local_dir(cwd.path().join(env_path))?;

        for entry in std::fs::read_dir(cwd.path())? {
            let path = entry?.path();

            assert!(path.is_dir() || path.is_file());

            if path.is_dir() {
                assert_eq!(path.strip_prefix(&cwd)?, env_path);
            } else {
                assert_eq!(path.strip_prefix(&cwd)?, env_path.join("env.toml"));
            }
        }

        assert_eq!(
            std::fs::File::open(cwd.path().join(".sysand/env.toml"))?
                .metadata()?
                .len(),
            DEFAULT_ENV_FILE_CONTENTS.len() as u64
        );

        let installed: Result<Vec<String>, sysand_core::env::local_directory::LocalReadError> =
            directory_environment.uris()?.into_iter().collect();
        let installed = installed?;

        assert_eq!(installed.len(), 0);

        Ok(())
    }

    fn make_two_version_env(
        cwd: &camino_tempfile::Utf8TempDir,
        uri: &str,
    ) -> Result<LocalDirectoryEnvironment, Box<dyn Error>> {
        let mut env = do_env_local_dir(cwd.path().join(DEFAULT_ENV_NAME))?;

        for version_str in ["1.0.0", "2.0.0"] {
            let info = InterchangeProjectInfoRaw {
                name: "multi_version_project".to_string(),
                publisher: None,
                description: None,
                version: version_str.to_owned(),
                license: None,
                maintainer: vec![],
                website: None,
                topic: vec![],
                usage: vec![],
            };

            let mut index = IndexMap::new();
            index.insert("Pkg".to_string(), String::from("Pkg.sysml"));

            let meta = InterchangeProjectMetadataRaw {
                index,
                created: format_created_now(),
                metamodel: None,
                includes_derived: None,
                includes_implied: None,
                checksum: None,
            };

            let mut source_project = InMemoryProject::default();
            source_project.put_project(&info, &meta, true)?;
            source_project.write_source(
                Utf8UnixPath::new("Pkg.sysml"),
                &mut Cursor::new("package Pkg;"),
                true,
            )?;

            env.put_project(uri, version_str, |p| {
                clone_project(&source_project, p, true).map(|_| ())
            })?;
        }

        Ok(env)
    }

    #[test]
    fn del_project_with_multiple_versions() -> Result<(), Box<dyn Error>> {
        let cwd = tempdir()?;
        let uri = "urn:sysand_test:multi";
        let mut env = make_two_version_env(&cwd, uri)?;

        // Both versions are present
        let mut versions: Vec<String> = env.versions(uri)?.into_iter().collect::<Result<_, _>>()?;
        versions.sort();
        assert_eq!(versions, vec!["1.0.0", "2.0.0"]);

        env.del_project_version(uri, "1.0.0")?;

        // Only 2.0.0 remains in metadata
        let versions: Vec<String> = env.versions(uri)?.into_iter().collect::<Result<_, _>>()?;
        assert_eq!(versions, vec!["2.0.0"]);

        assert!(env.get_project(uri, "1.0.0").is_err());
        assert!(env.get_project(uri, "2.0.0").is_ok());

        // URI still listed
        let uris: Vec<String> = env.uris()?.into_iter().collect::<Result<_, _>>()?;
        assert!(uris.contains(&uri.to_string()));

        // v1 project dir is fully removed
        let v1_dir = cwd.path().join(".sysand/lib/sysand_test.multi_1.0.0");
        assert!(!v1_dir.exists());

        // v2 project dir still has its files
        let v2_dir = cwd.path().join(".sysand/lib/sysand_test.multi_2.0.0");
        assert!(!ls_dir(&v2_dir).is_empty());

        // Persisted to disk: re-reading gives same result
        let env2 = LocalDirectoryEnvironment::read(cwd.path().join(".sysand"))?;
        let versions: Vec<String> = env2.versions(uri)?.into_iter().collect::<Result<_, _>>()?;
        assert_eq!(versions, vec!["2.0.0"]);

        Ok(())
    }

    #[test]
    fn del_uri_removes_all_versions() -> Result<(), Box<dyn Error>> {
        let cwd = tempdir()?;
        let uri = "urn:sysand_test:multi";
        let other_uri = "urn:sysand_test:other";
        let mut env = make_two_version_env(&cwd, uri)?;

        // Add an unrelated project to verify it is unaffected
        {
            let info = InterchangeProjectInfoRaw {
                name: "other_project".to_string(),
                publisher: None,
                description: None,
                version: "1.0.0".to_owned(),
                license: None,
                maintainer: vec![],
                website: None,
                topic: vec![],
                usage: vec![],
            };
            let mut index = IndexMap::new();
            index.insert("Other".to_string(), String::from("Other.sysml"));
            let meta = InterchangeProjectMetadataRaw {
                index,
                created: format_created_now(),
                metamodel: None,
                includes_derived: None,
                includes_implied: None,
                checksum: None,
            };
            let mut other_project = InMemoryProject::default();
            other_project.put_project(&info, &meta, true)?;
            other_project.write_source(
                Utf8UnixPath::new("Other.sysml"),
                &mut Cursor::new("package Other;"),
                true,
            )?;
            env.put_project(other_uri, "1.0.0", |p| {
                clone_project(&other_project, p, true).map(|_| ())
            })?;
        }

        env.del_uri(uri)?;

        // No versions for the deleted URI
        let versions: Vec<String> = env.versions(uri)?.into_iter().collect::<Result<_, _>>()?;
        assert!(versions.is_empty());

        // URI is gone from the listing
        let uris: Vec<String> = env.uris()?.into_iter().collect::<Result<_, _>>()?;
        assert!(!uris.contains(&uri.to_string()));

        // The other URI is unaffected
        assert!(uris.contains(&other_uri.to_string()));
        assert!(env.get_project(other_uri, "1.0.0").is_ok());

        // Both project dirs are fully removed
        let v1_dir = cwd.path().join(".sysand/lib/sysand_test.multi_1.0.0");
        let v2_dir = cwd.path().join(".sysand/lib/sysand_test.multi_2.0.0");
        assert!(!v1_dir.exists());
        assert!(!v2_dir.exists());

        // Persisted to disk: re-reading gives same result
        let env2 = LocalDirectoryEnvironment::read(cwd.path().join(".sysand"))?;
        let versions: Vec<String> = env2.versions(uri)?.into_iter().collect::<Result<_, _>>()?;
        assert!(versions.is_empty());

        Ok(())
    }

    #[test]
    fn env_manual_install() -> Result<(), Box<dyn Error>> {
        let cwd = tempdir()?;
        let mut directory_environment = do_env_local_dir(cwd.path().join(DEFAULT_ENV_NAME))?;

        let info = InterchangeProjectInfoRaw {
            name: "env_manual_install".to_string(),
            publisher: None,
            description: None,
            version: "1.2.3".to_owned(),
            license: None,
            maintainer: vec![],
            website: None,
            topic: vec![],
            usage: vec![],
        };

        let mut index = IndexMap::new();
        index.insert("SomePackage".to_string(), String::from("SomePackage.sysml"));

        let meta = InterchangeProjectMetadataRaw {
            index,
            created: format_created_now(),
            metamodel: None,
            includes_derived: None,
            includes_implied: None,
            checksum: None,
        };

        let mut source_project = InMemoryProject::default();

        source_project.put_project(&info, &meta, true)?;

        let source_path = Utf8UnixPath::new("SomePackage.sysml");
        let source_code = "package SomePackage;";

        source_project.write_source(source_path, &mut Cursor::new(source_code), true)?;

        directory_environment.put_project("urn:sysand_test:1", "1.2.3", |p| {
            clone_project(&source_project, p, true).map(|_| ())
        })?;

        let target_project = directory_environment.get_project("urn:sysand_test:1", "1.2.3")?;
        let (read_info, read_meta) = target_project.get_project()?;

        assert_eq!(read_info, Some(info.clone()));
        assert_eq!(read_meta, Some(meta.clone()));

        let mut read_source_code = String::new();

        target_project
            .read_source(source_path)?
            .read_to_string(&mut read_source_code)?;

        assert_eq!(read_source_code, source_code);

        assert_eq!(
            directory_environment
                .versions("urn:sysand_test:1")?
                .into_iter()
                .collect::<Result<Vec<String>, _>>()?,
            vec!["1.2.3"]
        );
        assert_eq!(
            directory_environment
                .uris()?
                .into_iter()
                .collect::<Result<Vec<String>, _>>()?,
            vec!["urn:sysand_test:1"]
        );

        assert_eq!(ls_dir(cwd.path()), vec![".sysand"]);
        assert_eq!(ls_dir(cwd.path().join(".sysand")), vec!["env.toml", "lib"]);
        assert_eq!(
            ls_dir(cwd.path().join(".sysand/lib").join("sysand_test.1_1.2.3")),
            vec![".meta.json", ".project.json", "SomePackage.sysml"]
        );

        let resolver = EnvResolver {
            env: directory_environment,
        };

        let resolved_project = do_info("urn:sysand_test:1", &resolver)?;

        assert_eq!(resolved_project, (info, meta));

        Ok(())
    }
}
