name: Java (Bindings)

on:
  push:
    branches: [main]
    tags: ["*"]
    paths:
      - "core/**"
      - "bindings/java/**"
      - "Cargo.*"
      - ".github/workflows/java.yml"
  pull_request:
    branches: [main]
    paths:
      - "core/**"
      - "bindings/java/**"
      - "Cargo.*"
      - ".github/workflows/java.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  UV_HTTP_RETRIES: 5
  UV_HTTP_TIMEOUT: 60

jobs:
  compile-bindings:
    name: Compile native bindings
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
          - macos-15-intel # x86
          - macos-latest # arm64

    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo build ...
        run: cargo build --locked --package sysand-java --release

      - uses: actions/setup-python@v6
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        with:
          python-version: "3.14"
      - name: Create version.txt
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: python bindings/java/scripts/java-builder.py create-version-file
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
      - name: Upload version.txt
        uses: actions/upload-artifact@v7
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        with:
          name: version
          path: version.txt
          if-no-files-found: error

      - name: Upload native bindings
        uses: actions/upload-artifact@v7
        with:
          name: native-bindings-${{ matrix.os }}
          path: |
            target/release/*.so
            target/release/*.dylib
            target/release/*.dll
          if-no-files-found: error
          retention-days: 5 # lower than default, many ~5 MB files

  build-jar:
    name: Build Java JAR
    needs: [compile-bindings]
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-java@v5
        with:
          java-version: "21" # to support JRE 21+
          distribution: temurin
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Download version.txt
        uses: actions/download-artifact@v8
        with:
          name: version
      - name: Download native bindings
        uses: actions/download-artifact@v8
        with:
          path: native-bindings
      - name: List native bindings
        run: ls -la native-bindings/*

      - name: Build JAR
        run: |
          python bindings/java/scripts/java-builder.py build \
              --use-existing-native-libs native-bindings \
              --use-release-build \
              ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE && '--sign-artifacts' || '' }}
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}

      - name: Build Sysand Maven plugin and run integration tests
        run: |
          python bindings/java/scripts/java-builder.py build-plugin \
              ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE && '--sign-artifacts' || '' }}
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}

      - name: Upload JARs
        uses: actions/upload-artifact@v7
        with:
          name: jars
          path: target/java
          if-no-files-found: error
          retention-days: 5 # lower than default, a ~160 MB file
      - name: Upload Maven plugin JAR
        uses: actions/upload-artifact@v7
        with:
          name: maven-plugin-jar
          path: target/java-plugin
          if-no-files-found: error
          # We need to include hidden files because integration tests use
          # .meta.json and .project.json files.
          include-hidden-files: true

  test-jar:
    name: Test Java JAR
    needs: build-jar
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
          - macos-15-intel # x86
          - macos-latest # arm64

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-java@v5
        with:
          java-version: "21" # to support JRE 21+
          distribution: temurin
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Download JARs
        uses: actions/download-artifact@v8
        with:
          name: jars
          path: target/java
      - name: Download version.txt
        uses: actions/download-artifact@v8
        with:
          name: version
      - name: List .jar files and more
        run: |
          find . -iname "*.jar"
          ls -la *
          ls -la target/*
          ls -la target/java/*
          ls -la target/java/target/*

      - name: Test Java JAR
        run: python bindings/java/scripts/java-builder.py test
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}

  nightly-release:
    name: Nightly Release
    needs: [build-jar, test-jar]
    if: ${{ github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write # for signing release artifacts
      contents: write # for uploading release artifacts
      attestations: write # for release artifact attestation

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-java@v5
        with:
          java-version: "21" # to support JRE 21+
          distribution: temurin
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Download native bindings
        uses: actions/download-artifact@v8
        with:
          name: jars
          path: target/java
      - name: Download Maven plugin JAR
        uses: actions/download-artifact@v8
        with:
          name: maven-plugin-jar
          path: target/java-plugin
      - name: Download version.txt
        uses: actions/download-artifact@v8
        with:
          name: version
      - name: List .jar files and more
        run: |
          find . -iname "*.jar"
          find target/java-plugin/target/it/

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "target/java/target/*.jar"

      - name: Deploy Java bindings
        run: python bindings/java/scripts/java-builder.py deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
