name: JS/WASM (Bindings)

on:
  push:
    branches: ["main"]
    paths:
      - "core/**"
      - "bindings/js/**"
      - "Cargo.*"
      - ".github/workflows/js-wasm.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "core/**"
      - "bindings/js/**"
      - "Cargo.*"
      - ".github/workflows/js-wasm.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  UV_HTTP_RETRIES: 5
  UV_HTTP_TIMEOUT: 60

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Test in Firefox
        run: |
          cd bindings/js
          export WASM_BINDGEN_USE_BROWSER=1
          wasm-pack test --headless --firefox

      - name: Test in Chrome
        run: |
          cd bindings/js
          export WASM_BINDGEN_USE_BROWSER=1
          wasm-pack test --headless --chrome

      - name: Build for Node.js and test
        run: |
          cd bindings/js
          npm install
          npm run test:browser
